export const PoductsList = [
    {
        name:'RCB Jersey ',
        brand:'jusball',
        rating:4,
        noOfRatings:67,
        price:229,
        off:77,
        gender:'',
        categoty:'jersey',
        season:'',
        loc:'',
        size:['s','m','l','xl','2xl'],
        color:["red","black"],
        images:["https://m.media-amazon.com/images/I/51F+JsBaS9L._UX679_.jpg","https://m.media-amazon.com/images/I/51-NOmRmmDL._UX679_.jpg"],
        instructions:["Care Instructions: Machine Wash",'Fit Type: Slim Fit','Material: 100% Polyester','Care Instructions: Hand Wash Only','Please Note: Colours may slightly vary depending on your screen brightness.','Standard Sizing For Kids: 7to10 years Chest 32" & 10to13 years Chest 36" 13to16 years Chest 38"','Standard Sizing For Mens: Small Chest 36" & Medium Chest 38" Large Chest 40" X-Large Chest 42" XX-Large Chest 44"']
    },
    {
        name:'Puma Men T-Shirt',
        brand:'puma',
        rating:5,
        noOfRatings:10,
        price:329,
        off:70,
        gender:'male',
        categoty:'t-shirt',
        season:'',
        loc:'',
        size:['s','m','l'],
        color:["white","black"],
        images:["https://m.media-amazon.com/images/I/5183oPzSqSL._UX679_.jpg","https://m.media-amazon.com/images/I/51nmHE5Nk+L._UX466_.jpg",'https://m.media-amazon.com/images/I/51pxHn16vAL._UX466_.jpg','https://m.media-amazon.com/images/I/41AUMQrhVBL._UX466_.jpg','https://m.media-amazon.com/images/I/51pSrNYBGnL._UX466_.jpg'],
        instructions:["Care Instructions: Machine Wash",'Fit Type: Regular Fit','Style Name:-Tee','Model Name:-Logo Box Tee','Please Note: Colours may slightly vary depending on your screen brightness.','Brand Color:-Cotton Black','Activity Group:-Sport Classics']
    },
    {
        name:' Chikankari Linen Sarees',
        brand:'SWORNOF',
        rating:4,
        noOfRatings:1268,
        price:949,
        off:73,
        gender:'female',
        categoty:'saree',
        season:'',
        loc:'',
        size:[],
        color:["blue","grey","pink","orange"],
        images:["https://m.media-amazon.com/images/I/41uF1XPtd0L.jpg","https://m.media-amazon.com/images/I/81rOL+EMAaS._UX522_.jpg",'https://m.media-amazon.com/images/I/918o1N31c1S._UY500_.jpg',"https://m.media-amazon.com/images/I/61lZ7KOyYsL._SY679._SX._UX._SY._UY_.jpg","https://m.media-amazon.com/images/I/81P285LyhiL._SY500._SX._UX._SY._UY_.jpg","https://m.media-amazon.com/images/I/81hHNG3Z8GL._SY500._SX._UX._SY._UY_.jpg"],
        instructions:['Care Instructions: Machine Wash','Material : Soft Cotton','Design : Lucknowi Chikankari Hand Weaving Work','Style : The Texture And Weight Of The Saree Brings Image Prints One Step Closer To The Originals And Invites Attention','Occasion : Sarees for women, festive, traditional saree. Best birth-day gift for your loved ones. Each piece is elegantly crafted and will surely add to your wardrobe']
    },
    {
        name:'Fit Trackpants',
        brand:'ENDEAVOUR',
        rating:3,
        noOfRatings:598,
        price:474,
        off:53,
        gender:'male',
        categoty:'Trackpants',
        season:'',
        loc:'',
        size:['s','l','xl'],
        color:["grey","black","green"],
        images:["https://m.media-amazon.com/images/I/61R11o1DC+S._UX679_.jpg","https://m.media-amazon.com/images/I/51fR7zwf5pS._UX679_.jpg","https://m.media-amazon.com/images/I/51DyrxaFjiS._UX679_.jpg","https://m.media-amazon.com/images/I/51hwQJUhkZS._SX679._SX._UX._SY._UY_.jpg"],
        instructions:['Care Instructions:Machine Wash','Fit Type: Regular Fit','Fabric :cotton ','Zippers on both side pocket; 92%POLYSTER 8%ELASTANE','Size: Free size, fit to waist size between 24 inches to 32 inches. Length -37 inches,Order Strictly According to Waist Size.','Rapid Dry and antimicrobial technology wicks sweat & dries fas','High Rise','To choose the right size- please refer Wide Leg size chart and how to measure image','Elasticated Waistband','Zip Fly With 2 Button Closure Elasticated Waistband','Long-lasting and no color loss even after multiple washes.']
    },
    {
        name:' Embellished Gown',
        brand:'Hopscotch',
        rating:5,
        noOfRatings:2168,
        price:2749,
        off:10,
        gender:'kids',
        categoty:'frock',
        season:'',
        loc:'',
        size:[],
        color:["black"],
        images:["https://m.media-amazon.com/images/I/71H3pYXQv3L._UX679_.jpg","https://m.media-amazon.com/images/I/71gQB+5AsaL._UX679_.jpg",'https://m.media-amazon.com/images/I/71QW9ZvghEL._UX679_.jpg'],
        instructions:['Care Instructions: Dry Clean Only','Fit Type: Regular','The actual product may differ slightly in color from the one illustrated in the images.','All Dimensions are in cms :- Gowns: Length: 91.5 cm , Chest: 67 cm , Shoulder: 27 cm']
    },
    {
        name:' Floral Printed Saree',
        brand:'Kanishka',
        rating:3,
        noOfRatings:268,
        price:749,
        off:69,
        gender:'female',
        categoty:'saree',
        season:'',
        loc:'',
        size:[],
        color:["light purple","grey","pink","orange","yellow"],
        images:["https://m.media-amazon.com/images/I/31V4WIcT3fL._UY606_.jpg","https://m.media-amazon.com/images/I/41CVa8NcgoL._SY500._SX._UX._SY._UY_.jpg",'https://m.media-amazon.com/images/I/31g-DtZNotL._SY500._SX._UX._SY._UY_.jpg',"https://m.media-amazon.com/images/I/61lZ7KOyYsL._SY679._SX._UX._SY._UY_.jpg","https://m.media-amazon.com/images/I/41PR36BzFZL._SY500._SX._UX._SY._UY_.jpg","https://m.media-amazon.com/images/I/3128a28YDkL._SY500._SX._UX._SY._UY_.jpg"],
        instructions:['Care Instructions: Dry Clean Only','Material : Soft Cotton','Design : Lucknowi Chikankari Hand Weaving Work','Style : The Texture And Weight Of The Saree Brings Image Prints One Step Closer To The Originals And Invites Attention','Occasion : Sarees for women, festive, traditional saree. Best birth-day gift for your loved ones. Each piece is elegantly crafted and will surely add to your wardrobe']
    },
    {
        name:' Lycra Crop Top',
        brand:'siril',
        rating:5,
        noOfRatings:368,
        price:259,
        off:78,
        gender:'female',
        categoty:'top',
        season:'',
        loc:'',
        size:['s','l','m','xl'],
        color:["lpista green","grey","pink","orange","yellow","red","blue"],
        images:["https://m.media-amazon.com/images/I/61yfZiZJ7kL._UY445_.jpg","https://m.media-amazon.com/images/I/61GRfSyvOJL._SY445._SX._UX._SY._UY_.jpg",'https://m.media-amazon.com/images/I/51Hx9y2YCSL._SY445._SX._UX._SY._UY_.jpg',"https://m.media-amazon.com/images/I/61lZ7KOyYsL._SY679._SX._UX._SY._UY_.jpg","https://m.media-amazon.com/images/I/61A65-9usrL._SY445._SX._UX._SY._UY_.jpg","https://m.media-amazon.com/images/I/61ITGFcSvaL._SY445._SX._UX._SY._UY_.jpg"],
        instructions:['Care Instructions:Machine Wash','Fit Type: Regular Fit','Fabric : Lycra ','Style: Crop Half Sleeve Shirt || Work: Knitted, Solid','Neck Style : Collared Neck','Length : 14.5Inch|Bust Size : 33Inch. Please select size from the filter box and refer the size chart']
    },
    {
        name:' Shorts for Men',
        brand:'Diruno',
        rating:4,
        noOfRatings:2168,
        price:349,
        off:10,
        gender:'men',
        categoty:'shorts',
        season:'',
        loc:'',
        size:['x','l','xxl','xxxl'],
        color:["black","blue","green","red"],
        images:["https://m.media-amazon.com/images/I/71WehhuihdL._UY606_.jpg","https://m.media-amazon.com/images/I/71RqgdoVDPL._UY606_.jpg",'https://m.media-amazon.com/images/I/61ZaSCUeQPL._UY606_.jpg',"https://m.media-amazon.com/images/I/61Yo39HiHcL._SY606._SX._UX._SY._UY_.jpg","https://m.media-amazon.com/images/I/61wWOQmEdNL._SY606._SX._UX._SY._UY_.jpg"],
        instructions:['Care Instructions: Hand-wash & Machine Wash','Fit Type: Regular','The actual product may differ slightly in color from the one illustrated in the images.','All Dimensions are in cms :- Gowns: Length: 91.5 cm , Chest: 67 cm , Shoulder: 27 cm','Features : Light Weight, Comfortable, Long Lasting, Strong, Moisture & Sweat Absorb, No-Wrinkling, Soft Hand Feeling, Quickly Dry.','Number Of Pockets : 2, Occasion : Gyming, Sports, Jogging, Athletic, Causal & Night Wear']
    },
    {
        name:' Lycra Crop Top',
        brand:'siril',
        rating:5,
        noOfRatings:368,
        price:259,
        off:78,
        gender:'female',
        categoty:'top',
        season:'',
        loc:'',
        size:['s','l','m','xl'],
        color:["lpista green","grey","pink","orange","yellow","red","blue"],
        images:["https://m.media-amazon.com/images/I/61yfZiZJ7kL._UY445_.jpg","https://m.media-amazon.com/images/I/61GRfSyvOJL._SY445._SX._UX._SY._UY_.jpg",'https://m.media-amazon.com/images/I/51Hx9y2YCSL._SY445._SX._UX._SY._UY_.jpg',"https://m.media-amazon.com/images/I/61lZ7KOyYsL._SY679._SX._UX._SY._UY_.jpg","https://m.media-amazon.com/images/I/61A65-9usrL._SY445._SX._UX._SY._UY_.jpg","https://m.media-amazon.com/images/I/61ITGFcSvaL._SY445._SX._UX._SY._UY_.jpg"],
        instructions:['Care Instructions:Machine Wash','Fit Type: Regular Fit','Fabric : Lycra ','Style: Crop Half Sleeve Shirt || Work: Knitted, Solid','Neck Style : Collared Neck','Length : 14.5Inch|Bust Size : 33Inch. Please select size from the filter box and refer the size chart']
    },
     {
        name:' Pyjama Set for Boys',
        brand:'AHHAAAA Kids',
        rating:4,
        noOfRatings:2168,
        price:949,
        off:76,
        gender:'kids',
        categoty:'pyjama',
        season:'',
        loc:'',
        size:['8 years'],
        color:["gold"],
        images:["https://m.media-amazon.com/images/I/81NPsP8uHFL._UY606_.jpg","https://m.media-amazon.com/images/I/71ju00zEbnL._UY606_.jpg",'https://m.media-amazon.com/images/I/71EsYn+6nFL._UY606_.jpg'],
        instructions:['Care Instructions: Dry Clean Only','Fit Type: Regular','The actual product may differ slightly in color from the one illustrated in the images.','All Dimensions are in cms :- Gowns: Length: 91.5 cm , Chest: 67 cm , Shoulder: 27 cm']
    },
    {
        name:' OOMPH! Crop Tops ',
        brand:'OOMPH!',
        rating:5,
        noOfRatings:368,
        price:199,
        off:78,
        gender:'female',
        categoty:'top',
        season:'',
        loc:'',
        size:['xs','s','l','m','xl'],
        color:["lpista green","grey","pink","orange","yellow","red","blue"],
        images:["https://m.media-amazon.com/images/I/61mRaOXVHUL._UY445_.jpg","https://m.media-amazon.com/images/I/618BYh7hVCL._UY445_.jpg",'https://m.media-amazon.com/images/I/61lc96aFQlL._UY445_.jpg',"https://m.media-amazon.com/images/I/61lZ7KOyYsL._SY679._SX._UX._SY._UY_.jpg","https://m.media-amazon.com/images/I/71nKg9a0xRL._UY445_.jpg","https://m.media-amazon.com/images/I/51s90e8NpKL._UY445_.jpg"],
        instructions:['Care Instructions:Machine Wash','Fit Type: Regular Fit','Fabric : Lycra ','Style: Crop Half Sleeve Shirt || Work: Knitted, Solid','Neck Style : Collared Neck','Length : 14.5Inch|Bust Size : 33Inch. Please select size from the filter box and refer the size chart','Suitable for women tops, top for women, tops, tops for women, women tops western latest, top, tops for women stylish latest, women top, jeans tops for women, tunic tops for women, top for women stylish, tops for girls, stylish tops for women, tunics for women stylish western, jeans tops for women stylish, casual tops for women, womens top, girls top, womens tops latest fashion, ladies top, tops women, top for women stylish western']
    },
    {
        name:'Gym Shorts',
        brand:'Fort Worth',
        rating:4,
        noOfRatings:2168,
        price:749,
        off:60,
        gender:'male',
        categoty:'shorts',
        season:'',
        loc:'',
        size:['xl'],
        color:["black","blue","green","red"],
        images:["https://m.media-amazon.com/images/I/61WOKE9h4JL._UX466_.jpg","https://m.media-amazon.com/images/I/61+RmM+yCvL._UX385_.jpg",'https://m.media-amazon.com/images/I/61eIU5t8FLL._UX385_.jpg',"https://m.media-amazon.com/images/I/61Yo39HiHcL._SY606._SX._UX._SY._UY_.jpg","https://m.media-amazon.com/images/I/61wWOQmEdNL._SY606._SX._UX._SY._UY_.jpg"],
        instructions:['Care Instructions: Hand-wash & Machine Wash','Fit Type: Regular','The actual product may differ slightly in color from the one illustrated in the images.','All Dimensions are in cms :- Gowns: Length: 91.5 cm , Chest: 67 cm , Shoulder: 27 cm','Features : Light Weight, Comfortable, Long Lasting, Strong, Moisture & Sweat Absorb, No-Wrinkling, Soft Hand Feeling, Quickly Dry.','Number Of Pockets : 2, Occasion : Gyming, Sports, Jogging, Athletic, Causal & Night Wear','10-INCH INSEAM: Whether you’re working out at the gym or running on the track, our men gym shorts have you covered. They are suitable for all your sports and workout activities including gym, cycling, running, basketball, football, tennis and more']
    },
    {
        name:' Lycra Crop Top',
        brand:'siril',
        rating:5,
        noOfRatings:368,
        price:259,
        off:78,
        gender:'female',
        categoty:'top',
        season:'',
        loc:'',
        size:['s','l','m','xl'],
        color:["lpista green","grey","pink","orange","yellow","red","blue"],
        images:["https://m.media-amazon.com/images/I/61yfZiZJ7kL._UY445_.jpg","https://m.media-amazon.com/images/I/61GRfSyvOJL._SY445._SX._UX._SY._UY_.jpg",'https://m.media-amazon.com/images/I/51Hx9y2YCSL._SY445._SX._UX._SY._UY_.jpg',"https://m.media-amazon.com/images/I/61lZ7KOyYsL._SY679._SX._UX._SY._UY_.jpg","https://m.media-amazon.com/images/I/61A65-9usrL._SY445._SX._UX._SY._UY_.jpg","https://m.media-amazon.com/images/I/61ITGFcSvaL._SY445._SX._UX._SY._UY_.jpg"],
        instructions:['Care Instructions:Machine Wash','Fit Type: Regular Fit','Fabric : Lycra ','Style: Crop Half Sleeve Shirt || Work: Knitted, Solid','Neck Style : Collared Neck','Length : 14.5Inch|Bust Size : 33Inch. Please select size from the filter box and refer the size chart']
    },
    {
        name:'Boys T-Shirt',
        brand:'Bon Organik',
        rating:4,
        noOfRatings:2168,
        price:219,
        off:78,
        gender:'kids',
        categoty:'T-shirt',
        season:'',
        loc:'',
        size:['5 years'],
        color:["gold"],
        images:["https://m.media-amazon.com/images/I/71zavfYqimL._UX679_.jpg"],
        instructions:['Care Instructions: Dry Clean Only','Fit Type: Regular','The actual product may differ slightly in color from the one illustrated in the images.','All Dimensions are in cms :- Gowns: Length: 91.5 cm , Chest: 67 cm , Shoulder: 27 cm']
    },
    
    {
        name:' Cotton Straight Top',
        brand:'Yash Gallery ',
        rating:5,
        noOfRatings:448,
        price:199,
        off:78,
        gender:'female',
        categoty:'top',
        season:'',
        loc:'',
        size:['xs','s','l','m','xl'],
        color:["lemon green","yellow","red"],
        images:["https://m.media-amazon.com/images/I/71Xj7h0zOkL._UY445_.jpg","https://m.media-amazon.com/images/I/61wxq7ERzcL._SY445._SX._UX._SY._UY_.jpg",'https://m.media-amazon.com/images/I/71KgYt8vV7L._SX385._SX._UX._SY._UY_.jpg'],
        instructions:['Care Instructions:Machine Wash','Fit Type: Regular Fit','Fabric : Lycra ','Style: Crop Half Sleeve Shirt || Work: Knitted, Solid','Neck Style : Collared Neck','Length : 14.5Inch|Bust Size : 33Inch. Please select size from the filter box and refer the size chart','Suitable for women tops, top for women, tops, tops for women, women tops western latest, top, tops for women stylish latest, women top, jeans tops for women, tunic tops for women, top for women stylish, tops for girls, stylish tops for women, tunics for women stylish western, jeans tops for women stylish, casual tops for women, womens top, girls top, womens tops latest fashion, ladies top, tops women, top for women stylish western']
    },
    {
        name:'Neck Hoodies',
        brand:'Goodtry',
        rating:4,
        noOfRatings:2168,
        price:599,
        off:70,
        gender:'female',
        categoty:'shorts',
        season:'',
        loc:'',
        size:['xl','xxl'],
        color:["black","blue"],
        images:["https://m.media-amazon.com/images/I/61EtKnMmD+S._UX679_.jpg","https://m.media-amazon.com/images/I/61UPFMNw-mS._UX679_.jpg",'https://m.media-amazon.com/images/I/61OGLub-AyS._UX679_.jpg'],
        instructions:['Care Instructions: Hand-wash & Machine Wash','Fit Type: Regular','The actual product may differ slightly in color from the one illustrated in the images.','All Dimensions are in cms :- Gowns: Length: 91.5 cm , Chest: 67 cm , Shoulder: 27 cm','Features : Light Weight, Comfortable, Long Lasting, Strong, Moisture & Sweat Absorb, No-Wrinkling, Soft Hand Feeling, Quickly Dry.','Number Of Pockets : 2, Occasion : Gyming, Sports, Jogging, Athletic, Causal & Night Wear','10-INCH INSEAM: Whether you’re working out at the gym or running on the track, our men gym shorts have you covered. They are suitable for all your sports and workout activities including gym, cycling, running, basketball, football, tennis and more']
    },
    {
        name:' Cotton Straight Top',
        brand:'Yash Gallery ',
        rating:5,
        noOfRatings:448,
        price:199,
        off:58,
        gender:'female',
        categoty:'top',
        season:'',
        loc:'',
        size:['xs','s','l','m','xl'],
        color:["off-white",],
        images:["https://m.media-amazon.com/images/I/81U1JyVPkcL._UY445_.jpg","https://m.media-amazon.com/images/I/71whSNGJ40L._UY445_.jpg",'https://m.media-amazon.com/images/I/813i+2ZruXL._UY445_.jpg'],
        instructions:['Care Instructions:Machine Wash','Fit Type: Regular Fit','Fabric :cotton ','Style: Crop Sleeve Shirt || Work: Knitted, Solid','Neck Style : Collared Neck','Length : 14.5Inch|Bust Size : 33Inch. Please select size from the filter box and refer the size chart',]
    },
    {
        name:' Waistband Wide Jeans',
        brand:'AKA CHIC ',
        rating:4,
        noOfRatings:1448,
        price:899,
        off:78,
        gender:'female',
        categoty:'jeans',
        season:'',
        loc:'',
        size:['l','xl'],
        color:["off-white",],
        images:["https://m.media-amazon.com/images/I/71PjLhe-PSL._UX679_.jpg","https://m.media-amazon.com/images/I/71Ga8ur+qyL._UX679_.jpg",'https://m.media-amazon.com/images/I/71Kc-1xKgAL._UX679_.jpg','https://m.media-amazon.com/images/I/A1PKeikaXVL._UX679_.jpg'],
        instructions:['Care Instructions:Machine Wash','Fit Type: Regular Fit','Fabric :cotton ','High Rise','Wide Leg','To choose the right size- please refer Wide Leg size chart and how to measure image','Elasticated Waistband']
    },
    {
        name:'Girls Jumpsuit',
        brand:'nauti nati',
        rating:4,
        noOfRatings:2168,
        price:619,
        off:55,
        gender:'kids',
        categoty:'jump suit',
        season:'',
        loc:'',
        size:['5 years'],
        color:["multicolor"],
        images:["https://m.media-amazon.com/images/I/616YLhVjlkL._UY606_.jpg","https://m.media-amazon.com/images/I/61jCMliqtpL._UY606_.jpg","https://m.media-amazon.com/images/I/61Kr5flCTOL._UY606_.jpg"],
        instructions:['Care Instructions: Dry Clean Only','Fit Type: Regular','The actual product may differ slightly in color from the one illustrated in the images.','Sleeve type: Sleeveless']
    },
    {
        name:' Women Jeans',
        brand:'AKA CHIC ',
        rating:3,
        noOfRatings:1448,
        price:1099,
        off:65,
        gender:'female',
        categoty:'jeans',
        season:'',
        loc:'',
        size:['l','xl','xxl','xxxl'],
        color:["pink","blue","beige"],
        images:["https://m.media-amazon.com/images/I/51bmHRHla6L._UY606_.jpg","https://m.media-amazon.com/images/I/510OnIFTWjL._UY606_.jpg",'https://m.media-amazon.com/images/I/81n+wBWBPTL._SX466._SX._UX._SY._UY_.jpg','https://m.media-amazon.com/images/I/811Yj8IY4JL._SX466._SX._UX._SY._UY_.jpg','https://m.media-amazon.com/images/I/51ifzItB9-L._SY606._SX._UX._SY._UY_.jpg','https://m.media-amazon.com/images/I/51x1CiG4NyL._SY606._SX._UX._SY._UY_.jpg'],
        instructions:['Care Instructions:Machine Wash','Fit Type: Regular Fit','Fabric :cotton ','High Rise','Wide Leg','To choose the right size- please refer Wide Leg size chart and how to measure image','Elasticated Waistband','Zip Fly With 2 Button Closure Elasticated Waistband']
    },
    {
        name:'Regular Fit Cigarette Pant',
        brand:'FASHION GALLERY',
        rating:4,
        noOfRatings:1448,
        price:299,
        off:50,
        gender:'female',
        categoty:'jeans',
        season:'',
        loc:'',
        size:['l'],
        color:["white"],
        images:["https://m.media-amazon.com/images/I/41X99kvhl6L._UY550_.jpg","https://m.media-amazon.com/images/I/31d49AzszNL._UY550_.jpg",],
        instructions:['Care Instructions:Machine Wash','Fit Type: Regular Fit','Fabric :cotton ','High Rise','Wide Leg','To choose the right size- please refer Wide Leg size chart and how to measure image','Elasticated Waistband','Zip Fly With 2 Button Closure Elasticated Waistband','Clouser type : 2" inch Standard Elasticated waist band for smooth grip of waist.The Cigarette Pant has Stratechable Fabric Which Gives All Around Comfort. The Cigarette Pant has interlock inside part and colour of variation available for Pant. This Cigarette Pant has Heavy and smooth Elastic material used in waist part which is very smooth and long lasting.The Fabric of Cigarette Pant is Premium quality Rayon Slub which is Skin Friendly & comfortable.']
    },
    {
        name:' Skinny Fit High Rise Jeans',
        brand:'Miss Chase',
        rating:3,
        noOfRatings:748,
        price:799,
        off:62,
        gender:'female',
        categoty:'jeans',
        season:'',
        loc:'',
        size:['s','l','xl','xxl'],
        color:["black","blue","beige"],
        images:["https://m.media-amazon.com/images/I/71a03OHZiVL._UY679_.jpg","https://m.media-amazon.com/images/I/61xFEBIwiwL._UY550_.jpg",'https://m.media-amazon.com/images/I/81w96fpJjcL._SY550._SX._UX._SY._UY_.jpg','https://m.media-amazon.com/images/I/718LoOaI2fL._SY550._SX._UX._SY._UY_.jpg'],
        instructions:['Care Instructions:Machine Wash','Fit Type: Regular Fit','Fabric :cotton ','High Rise','Length(inches): XS(26)-39, S(28)-39, M(30)-39, L(32)-39, XL(34)-39','Waist(inches): XS(26)-25, S(28)-27, M(30)-29, L(32)-31, XL(34)-33; Hip(inches): XS(26)-33, S(28)-35, M(30)-37, L(32)-39, XL(34)-41','To choose the right size- please refer Wide Leg size chart and how to measure image','Elasticated Waistband','Zip Fly With 2 Button Closure Elasticated Waistband']
    },
    {
        name:'Cotton Blend Jumpsuits',
        brand:'CHESTA ',
        rating:4,
        noOfRatings:2168,
        price:499,
        off:49,
        gender:'kids',
        categoty:'jump suit',
        season:'',
        loc:'',
        size:['s','m','l','xl','2xl'],
        color:["multicolor"],
        images:["https://m.media-amazon.com/images/I/316jo2lhqTL._UX466_.jpg","https://m.media-amazon.com/images/I/31eAvaivfAL._UX466_.jpg"],
        instructions:['Care Instructions: Dry Clean Only','Fit Type: Regular','The actual product may differ slightly in color from the one illustrated in the images.','Sleeve type: Sleeveless','Fabric: soft premium quality Cotton Blend top, with denim shorts with Rayon lining for utmost comfort Inner body also comes with same soft Rayon with silk which helps in making the dress comfortable to wear for long time']
    },
    {
        name:'Regular T-Shirt',
        brand:'Bon Organik',
        rating:3,
        noOfRatings:2168,
        price:229,
        off:62,
        gender:'kids',
        categoty:'shirt',
        season:'',
        loc:'',
        size:['s','l'],
        color:["blue"],
        images:["https://m.media-amazon.com/images/I/71WSUWjsgPL._UY606_.jpg",'https://m.media-amazon.com/images/I/718EzbEzSJL._UY606_.jpg'],
        instructions:['Care Instructions: Dry Clean Only','Fit Type: Regular','The actual product may differ slightly in color from the one illustrated in the images.','All Dimensions are in cms :- Gowns: Length: 91.5 cm , Chest: 67 cm , Shoulder: 27 cm']
    },
    {
        name:'ulticolor Ankle-Length Leggings',
        brand:'STYLE GRID',
        rating:3,
        noOfRatings:598,
        price:599,
        off:67,
        gender:'female',
        categoty:'jeans',
        season:'',
        loc:'',
        size:['xl'],
        color:["multicolor"],
        images:["https://m.media-amazon.com/images/I/71tkGmUvkKL._UX679_.jpg"],
        instructions:['Care Instructions:Machine Wash','Fit Type: Regular Fit','Fabric :cotton ','Size: Free size, fit to waist size between 24 inches to 32 inches. Length -37 inches,Order Strictly According to Waist Size.','High Rise','To choose the right size- please refer Wide Leg size chart and how to measure image','Elasticated Waistband','Zip Fly With 2 Button Closure Elasticated Waistband','Long-lasting and no color loss even after multiple washes.']
    },
    {
        name:' Polyester Wear Saree',
        brand:'Shiv Textiles',
        rating:4,
        noOfRatings:1268,
        price:949,
        off:62,
        gender:'female',
        categoty:'saree',
        season:'',
        loc:'',
        size:[],
        color:["blue","pink","yellow"],
        images:["https://m.media-amazon.com/images/I/410Kw-Y21XL._UX522_.jpg","https://m.media-amazon.com/images/I/41+suBosmwL._UX522_.jpg",'https://m.media-amazon.com/images/I/41ii8q1admL._UX522_.jpg',"https://m.media-amazon.com/images/I/71PlM3dYIHL._SY550._SX._UX._SY._UY_.jpg","https://m.media-amazon.com/images/I/81P285LyhiL._SY500._SX._UX._SY._UY_.jpg","https://m.media-amazon.com/images/I/71MK5rUI-kL._SY550._SX._UX._SY._UY_.jpg"],
        instructions:['Care Instructions: Hand Wash Only','Material : Soft Cotton','Design : Lucknowi Chikankari Hand Weaving Work','Style : The Texture And Weight Of The Saree Brings Image Prints One Step Closer To The Originals And Invites Attention','Occasion : Sarees for women, festive, traditional saree. Best birth-day gift for your loved ones. Each piece is elegantly crafted and will surely add to your wardrobe','This Is Pre Stitched Saree Ready To Wear || You Will Get Ready For Party In One Minute Saree For Women','Latest design sarees for women: Trendy and contemporary sarees with modern designs and patterns, keeping up with the latest fashion trends for women.']
    },
   
    {
        name:' Lace Georgette Saree',
        brand:'SIRIL',
        rating:4,
        noOfRatings:1570,
        price:1999,
        off:74,
        gender:'female',
        categoty:'saree',
        season:'',
        loc:'',
        size:[],
        color:["yellow","black","red","coral pink"],
        images:["https://m.media-amazon.com/images/I/71h1lAi7c5L._UY550_.jpg","https://m.media-amazon.com/images/I/81AcvJxe-lL._UY550_.jpg",'https://m.media-amazon.com/images/I/81DjIb8WOmL._UY550_.jpg',"image.png","https://m.media-amazon.com/images/I/81P285LyhiL._SY500._SX._UX._SY._UY_.jpg","https://m.media-amazon.com/images/I/71QQVt38r3L._SY550._SX._UX._SY._UY_.jpg","https://m.media-amazon.com/images/I/71vnAfwbVDL._SY550._SX._UX._SY._UY_.jpg","https://m.media-amazon.com/images/I/71c-a9uroJL._SY550._SX._UX._SY._UY_.jpg"],
        instructions:['Care Instructions: Hand Wash Only','Material : Soft Cotton','Design : Lucknowi Chikankari Hand Weaving Work','Style : The Texture And Weight Of The Saree Brings Image Prints One Step Closer To The Originals And Invites Attention','Occasion : Sarees for women, festive, traditional saree. Best birth-day gift for your loved ones. Each piece is elegantly crafted and will surely add to your wardrobe','This Is Pre Stitched Saree Ready To Wear || You Will Get Ready For Party In One Minute Saree For Women','Latest design sarees for women: Trendy and contemporary sarees with modern designs and patterns, keeping up with the latest fashion trends for women.']
    },
    {
        name:'CSK Jersey Dhoni 7 2023',
        brand:'Generic Store',
        rating:3,
        noOfRatings:4,
        price:399,
        off:60,
        gender:'',
        categoty:'jersey',
        season:'',
        loc:'',
        size:['s','m','l','xl'],
        color:["yellow"],
        images:["https://m.media-amazon.com/images/I/61CH4-aSFIL._UX522_.jpg"],
        instructions:["Care Instructions: Machine Wash",'Fit Type: Slim Fit','Material: 100% Polyester','Care Instructions: Hand Wash Only','Please Note: Colours may slightly vary depending on your screen brightness.','Standard Sizing For Kids: 7to10 years Chest 32" & 10to13 years Chest 36" 13to16 years Chest 38"','Standard Sizing For Mens: Small Chest 36" & Medium Chest 38" Large Chest 40" X-Large Chest 42" XX-Large Chest 44"']
    },
    {
        name:'Nike Boys Mercurial ',
        brand:'Nike',
        rating:4,
        noOfRatings:1107,
        price:40801,
        off:'',
        gender:'male',
        categoty:'Shoes',
        season:'',
        loc:'',
        size:['x','l','xl'],
        color:["Black/White"],
        images:["https://m.media-amazon.com/images/I/51UDX+yrWXS._UX625_.jpg"],
        instructions:["Water Resistance Level: Not Water Resistant"]
    },
   
{
    name:"Kurta and Dhoti Pant Set",
    brand:"JBN Creation",
    rating:4,
    noOfRatings:73,
    price:562,
    off:75,
    gender:'Kids',
    category:'Kurta',
    season:'',
    loc:'',
    size:['s','xl'],
    color:["Wine"],
    images:["https://m.media-amazon.com/images/I/51oViSc5NOL._UY445_.jpg","https://m.media-amazon.com/images/I/513GSW7vD4L._UY550_.jpg",
"https://m.media-amazon.com/images/I/510lNTpXAIL._UL1440_.jpg","https://m.media-amazon.com/images/I/51GZraCmimL._UL1440_.jpg","https://m.media-amazon.com/images/I/81QVu25S9tL._UL1440_.jpg"],
    instructions:['Care Instructions: Dry Clean Only','Fit type:Regular',
'Fabric: Cotton Silk Blend | Contents: Kurta and Dhoti Pant Set',
'Straight Kurta With Mandarin Collar And Button Closure Along With Versatile Cowl Dhoti To Look Your Dashing Best',
'We manufacture kids wear for boys 1-2 years, 2-3 years, 3-4 years, 4-5 years, 5-6 years, 6-7 years, 7-8 years, 8-9 years, 9-10 years, 10-11 years, 11-12 years, 12-13 years, 13-14 years, 14-15 years and kids wear for baby boys 0-6 months, 6-12 months, 12-18 months, 18-24 months.',
"All our kurtas, Sherwani, Indowestern and Nehru Jackets have loosening over the body measurement. Measurements shown in images or the size chart section are garment measurements, so take adequate 5-6 inches loosening over the little champion's body measurement to get the right fit. Our kurtas are Medium length and Regular Fit. Our Kurta fitting is usually slightly relaxed compared to a Regular Shirt's fitting. Select your Kurta size based on your chest dimension.','Save it for janmashtami dress for baby boy as well, just add a bansuri or a flute to make this a krishna dress for baby boy! These kids ethnic wear for boys under boys clothing are also used as pathani suit for boys stylish, jubba for boys, panjabi for boys or khan dress for boys stylish. The bottom is a patiala style cowl pattern draped dhoti pant. Most material used for kurta under 300 tensil count only.','Wash Care Instructions: Dry Clean preferably or cold light wash. Disclaimer: We have made a consistent effort to make the colors and finishes similar to the image of the products you see on screen. However, the actual product and the images on the website can differ! Customer's discretion is advised."]
},
{
    name:"ishin Women's Viscose Rayon Anarkali Embellished Kurta",
    brand:"Ishin",
    rating:4,
    noOfRatings:108,
    price:1403,
    off:72,
    gender:'Women',
    category:'Kurta',
    season:'',
    loc:'',
    size:['s','m','l','xl','2xl'],
    color:["blue","Pink","red","red & orange","yellow"],
    images:["https://m.media-amazon.com/images/I/71p66iHujBL._UX522_.jpg","https://m.media-amazon.com/images/I/71kmZOjqisL._UX385_.jpg","https://m.media-amazon.com/images/I/81SDcCvVmGL._UX385_.jpg","https://m.media-amazon.com/images/I/71w7kH1Wv6L._UX385_.jpg","https://m.media-amazon.com/images/I/71v13I2i1dL._UX385_.jpg","https://m.media-amazon.com/images/I/71z4wrTiXxL._UX385_.jpg" ],
    instructions: ['Care Instructions:  Dry Clean Only','Fit Type:Regular,Pink Bandhani Embroidered Anarkali Kurta, has Round Neck, Three-Quarter Sleeves, Flared hem, has No Slits',
'Package Contents :- 1 Kurta ,The Garment Measurement of Small Size is 36" inches Which Fits to the Actual Body Bust of Size 34" inches Comfortably. The Same Criteria will Follow for Other Sizes Like Medium, Large, X-Large, XX-Large. We recommend you buy a size larger.','FITS ALL OCCASIONS: It makes a great addition to your wardrobe for festive wear, dailywear, casual wear, office wear or evening wear with its evergreen design also this Kurti makes it a Wonderful gifting package for any occasion. ','Ishin has many categories of women wear like Kurta Set , Kurta Palazzo set, Salwar suits , Kurta trouser set, Kurta Sharara set, Kurtas for Women, Trending Kurta For Women, Anarkali Kurtas, Bandhani Kurtas, Cotton Dress, Flared Dresses, Casual Wear, Party Outfit , Kaftan Dresses, Lurex Top, Cotton Top, Peplum TOP, Short Top. Casual Wear Sarees, Georgette Saree, Chiffon Sarees, Poly Silk Sarees, Art Silk Sarees, Festive Wear Sarees.']
},
{
    name:'Amayra Mens Cotton Printed Straight Kurta',
    brand:'Amayra',
    rating:3,
    noOfRatings:8,
    price:429,
    off:79,
    gender:'male',
    categoty:'Kurta',
    season:'',
    loc:'',
    size:['m','l','xl'],
    color:["blue"],
    images:["https://m.media-amazon.com/images/I/61+OyZzVSWS._UY879_.jpg","https://m.media-amazon.com/images/I/51uqqElvlNS._UY879_.jpg"],
    instructions:["Care Instructions: Machine Wash","Fit Type: Regular","Material Composition: 100% Cotton"]
},
{
    name:'Woman Cotton Kurta',
    brand:'W',
    rating:4,
    noOfRatings:10,
    price:527,
    off:65,
    gender:'female',
    categoty:'Kurta',
    season:'',
    loc:'',
    size:[''],
    color:["Light Green"],
    images:["https://m.media-amazon.com/images/I/71+6KSvCw0L._UY879_.jpg","https://m.media-amazon.com/images/I/5186Uy6vQ7L._UY879_.jpg",'https://m.media-amazon.com/images/I/71IZlgzdhBL._UY879_.jpg'],
    instructions:["Care Instructions: Machine Wash","Fit Type: Regular","Lime Yellow Placement Print Straight Kurta"]
},
{
    name:'Max Kurta',
    brand:'Max',
    rating:4,
    noOfRatings:9,
    price:339,
    off:32,
    gender:'female',
    categoty:'Kurta',
    season:'',
    loc:'',
    size:['s','m','l','xl'],
    color:["MUSTARD"],
    images:["https://m.media-amazon.com/images/I/81T7HuW8l1L._UY879_.jpg","https://m.media-amazon.com/images/I/81uRv2m0pML._UY879_.jpg",'https://m.media-amazon.com/images/I/91iNuYb3RcL._UY879_.jpg'],
    instructions:["Care Instructions: Machine Wash","Fit Type: Straight","Fabric : RAYON"]
},
{
    name:'AKHILAM Womens Embroidered Work Organza Saree',
    brand:'AKHILAM',
    rating:4,
    noOfRatings:10,
    price:799,
    off:71,
    gender:'female',
    categoty:'Embroidered Work Organza Saree',
    season:'',
    loc:'',
    size:[''],
    color:["Olive","Turquoise"],
    images:["https://m.media-amazon.com/images/I/61H3hcwRTwL._SY879._SX._UX._SY._UY_.jpg","https://m.media-amazon.com/images/I/71kQVaik56L._SY879._SX._UX._SY._UY_.jpg",'https://m.media-amazon.com/images/I/71TdmEAjCPL._SY879._SX._UX._SY._UY_.jpg'],
    instructions:["Care Instructions: Machine","WashFabric :- Organza Saree with Silk Blend Blouse","Saree Work Detail :- Embroidered","Blouse Work Detail:- FloralSaree","Length: Saree- 5.5","Blouse Piece Length: 0.8","MtrPackage Contains :- 1 Saree with 1 unstitched Blouse Piece"]
},
{
    name:' Golden Zari Butta Saree ',
    brand:'leeza store',
    rating:3,
    noOfRatings:549,
    price:549,
    off:74,
    gender:'female',
    categoty:'saree',
    season:'',
    loc:'',
    size:[],
    color:["maroon","black","red","coral pink"],
    images:["https://m.media-amazon.com/images/I/919Uu73NihL._UY679_.jpg","https://m.media-amazon.com/images/I/A15KLoZanBL._UY550_.jpg",'https://m.media-amazon.com/images/I/91Y-Bsq7rwL._UY550_.jpg',"https://m.media-amazon.com/images/I/91onVV4FakL._SY550._SX._UX._SY._UY_.jpg","https://m.media-amazon.com/images/I/81P285LyhiL._SY500._SX._UX._SY._UY_.jpg","https://m.media-amazon.com/images/I/91SlckUXtQL._SY550._SX._UX._SY._UY_.jpg","https://m.media-amazon.com/images/I/91m5psjohWL._SY550._SX._UX._SY._UY_.jpg"],
    instructions:['Care Instructions: Hand Wash Only','Type: Banarasi Traditional Saree','Fabric: Saree: Lichi Silk Blend','Blouse: Poly Silk','Style : The Texture And Weight Of The Saree Brings Image Prints One Step Closer To The Originals And Invites Attention','Occasion : Sarees for women, festive, traditional saree. Best birth-day gift for your loved ones. Each piece is elegantly crafted and will surely add to your wardrobe','This Is Pre Stitched Saree Ready To Wear || You Will Get Ready For Party In One Minute Saree For Women','Latest design sarees for women: Trendy and contemporary sarees with modern designs and patterns, keeping up with the latest fashion trends for women.']
},
{
    name:' Brasso Printed Saree ',
    brand:'Winza',
    rating:3,
    noOfRatings:649,
    price:5549,
    off:74,
    gender:'female',
    categoty:'saree',
    season:'',
    loc:'',
    size:[],
    color:["purple","black","red","rama"],
    images:["https://m.media-amazon.com/images/I/81NszQM5rfL._UY550_.jpg","https://m.media-amazon.com/images/I/81Upuxz5T2L._UY550_.jpg",'https://m.media-amazon.com/images/I/81QADki5nmL._UY550_.jpg',"https://m.media-amazon.com/images/I/81P9bztDd0L._SY550._SX._UX._SY._UY_.jpg","https://m.media-amazon.com/images/I/8147EAvnApL._SY550._SX._UX._SY._UY_.jpg",],
    instructions:['Care Instructions: Hand Wash Only','Type: Banarasi Traditional Saree','Fabric: Saree: Lichi Silk Blend','Blouse: Poly Silk','Style : The Texture And Weight Of The Saree Brings Image Prints One Step Closer To The Originals And Invites Attention','Occasion : Sarees for women, festive, traditional saree. Best birth-day gift for your loved ones. Each piece is elegantly crafted and will surely add to your wardrobe','This Is Pre Stitched Saree Ready To Wear || You Will Get Ready For Party In One Minute Saree For Women','Latest design sarees for women: Trendy and contemporary sarees with modern designs and patterns, keeping up with the latest fashion trends for women.']
},
{
    name:'Prited Dress',
    brand:'Jwalin',
    rating:5,
    noOfRatings:78,
    price:799,
    off:68,
    gender:'girls',
    categoty:'dress',
    season:'',
    loc:'',
    size:['s','m','l'],
    color:["rama green"],
    images:["https://m.media-amazon.com/images/I/8151EfNw4QL._UY879_.jpg","https://m.media-amazon.com/images/I/81Ig289fq-L._UY879_.jpg"],
    instructions:["Care Instructions: Hand Wash Only",'Fit Type: Regular','Fabric: Crepe','Please Note: Colours may slightly vary depending on your screen brightness.','Wash Care: Cold Water Wash/ Do Not Iron on Print','Standard Sizing For Kids: 7to10 years Chest 32" & 10to13 years Chest 36" 13to16 years Chest 38"']

},
{
    name:'Adiva girls midi dress ',
    brand:'Adiva',
    rating:3.5,
    noOfRatings:20,
    price:399,
    off:80,
    gender:'girls',
    categoty:'skirt',
    season:'summer',
    loc:'',
    size:['s','m','l','xl','2xl'],
    color:["blue"],
    images:["https://m.media-amazon.com/images/I/51R8dXRm6BL._UX679_.jpg","https://m.media-amazon.com/images/I/51Ec-N5ZlOL._UX679_.jpg"],
    instructions:["Care Instructions: Hand Wash Only",'Fit Type: Regular','Fabric: jeans','Please Note: Colours may slightly vary depending on your screen brightness.','Wash Care: Cold Water Wash']
},
{
    name:'Naughty Ninos girls Pinafore',
    brand:'Naughty Ninos',
    rating:4,
    noOfRatings:142,
    price:659,
    off:61,
    gender:'girls',
    categoty:'dress',
    season:'summer',
    loc:'',
    size:['s','m','l','xl','2xl'],
    color:["peachy pink"],
    images:["https://m.media-amazon.com/images/I/51iVofb1R5L._UY879_.jpg","https://m.media-amazon.com/images/I/51SmqvCmo2L._UY879_.jpg"],
    instructions:["Care Instructions: Machine Wash",'Fit Type: Regular','Fabric: 100% cotton dress,inside vest made with soft strethable cotton fabric and front chest embroidred ','Please Note: Colours may slightly vary depending on your screen brightness.']
},
{
    name:'knee length dress ',
    brand:'Wish Karo',
    rating:4.3,
    noOfRatings:237,
    price:569,
    off:72,
    gender:'girls',
    categoty:'dress',
    season:'',
    loc:'',
    size:['s','m','l','xl','2xl'],
    color:["multicolor"],
    images:["https://m.media-amazon.com/images/I/51F0749owGL._UY879_.jpg","https://m.media-amazon.com/images/I/51deiWXhY2L._UY879_.jpg"],
    instructions:["Care Instructions: Dry Clean Only",'Fit Type: Regular','Fabric: net ','Style:A-line','Pattern: PLain/Solid','Please Note: Colours may slightly vary depending on your screen brightness.']
},
{
    name:'OMLI girls Midi Dress ',
    brand:'OMLI',
    rating:3.5,
    noOfRatings:235,
    price:398,
    off:60,
    gender:'girls',
    categoty:'frock',
    season:'',
    loc:'',
    size:['s','m','l','xl','2xl'],
    color:["grey and pink"],
    images:["https://m.media-amazon.com/images/I/71ymXjmTXPL._UX679_.jpg","https://m.media-amazon.com/images/I/717T8ee2dnL._UX679_.jpg"],
    instructions:["Care Instructions: Hand Wash Only",'Fit Type: Regular','Fabric: net ','Pattern: PLain/Solid','Material Composition: Satin Blend','Please Note: Colours may slightly vary depending on your screen brightness.']
},
{
    name:'Zolario 3 piece Boys suit ',
    brand:'Zolario',
    rating:4,
    noOfRatings:666,
    price:945,
    off:53,
    gender:'male',
    categoty:'suit',
    season:'',
    loc:'',
    size:['s','m','l','xl','2xl'],
    color:["grey and black"],
    images:["https://m.media-amazon.com/images/I/61Bs8dETthL._UX679_.jpg","https://m.media-amazon.com/images/I/71ba3+VZa5L._UX679_.jpg"],
    instructions:["Care Instructions: Machine Wash",'Fit Type: Regular','Fabric: net ','IMPORTANT: Latest Designer, Regular Size, Fine Printed, Good Quality Material','Please Note: Colours may slightly vary depending on your screen brightness.']
},
{
    name:'Doodle girls dresses ',
    brand:'Doodle',
    rating:4,
    noOfRatings:269,
    price:879,
    off:45,
    gender:'girls',
    categoty:'dress',
    season:'summer',
    loc:'',
    size:['s','m','l','xl','2xl'],
    color:["pink"],
    images:["https://m.media-amazon.com/images/I/517SpI6jE1L._UX679_.jpg","https://m.media-amazon.com/images/I/51wHBB9ApIL._UX679_.jpg"],
    instructions:["Care Instructions: Machine Wash",'Fit Type: Regular','Material Quality: Its Made Of Soft Material. Skin Friendly Material, Which Is Gentle On Childs Sensitive Skin.','Sleeve Type: Sleeveless; Material Composition: Satin','Please Note: Colours may slightly vary depending on your screen brightness.']
}, {
    name:'Puma Men T-Shirt',
    brand:'puma',
    rating:5,
    noOfRatings:10,
    price:329,
    off:70,
    gender:'male',
    category:'shirt',
    season:'',
    loc:'',
    size:['s','m','l'],
    color:["white","black"],
    images:["https://m.media-amazon.com/images/I/5183oPzSqSL._UX679_.jpg","https://m.media-amazon.com/images/I/51nmHE5Nk+L._UX466_.jpg",'https://m.media-amazon.com/images/I/51pxHn16vAL._UX466_.jpg','https://m.media-amazon.com/images/I/41AUMQrhVBL._UX466_.jpg','https://m.media-amazon.com/images/I/51pSrNYBGnL._UX466_.jpg'],
    instructions:["Care Instructions: Machine Wash",'Fit Type: Regular Fit','Style Name:-Tee','Model Name:-Logo Box Tee','Please Note: Colours may slightly vary depending on your screen brightness.','Brand Color:-Cotton Black','Activity Group:-Sport Classics']
},
{
    name:"Levi's Men Sweatshirt",
    brand:"Levi's",
    rating:4,
    noOfRatings:281,
    price:799,
    off:78,
    gender:'male',
    category:'shirt',
    season:'Winter',
    loc:'',
    size:['s','m','l','xl','2xl'],
    color:["red","black","white","blue"],
    images:["https://m.media-amazon.com/images/I/715BPYueBmL._UX569_.jpg","https://m.media-amazon.com/images/I/71cPtygYBfL._UX569_.jpg","https://m.media-amazon.com/images/I/513KzVheSRL._UY741_.jpg","https://m.media-amazon.com/images/I/91k-dPoKMAL._UX569_.jpg","https://m.media-amazon.com/images/I/61hrjoKhGRL._UX569_.jpg","https://m.media-amazon.com/images/I/91CAyHaci7L._UX569_.jpg"],
    instructions:["Care Instructions: Machine Wash",'Fit Type: Regular']
},
{
    name:"Symbol Men Formal Shirt",
    brand:"Symbol Store",
    rating:4,
    noOfRatings:5915,
    price:609,
    off:64,
    gender:'male',
    category:'Formal',
    season:'',
    loc:'',
    size:['s','m','l','xl','2xl'],
    color:["white","black","Bottle Green","Grey","Wine","Yellow","Navy","Rust"],
    images:["https://m.media-amazon.com/images/I/61GtS6IrR7L._UY550_.jpg","https://m.media-amazon.com/images/I/71sJSugM-YL._UY550_.jpg","https://m.media-amazon.com/images/I/71CaokWtkpL._UY550_.jpg","https://m.media-amazon.com/images/I/71yUi78kEwL._UY550_.jpg","https://m.media-amazon.com/images/I/71M6dUoXvIL._UY550_.jpg","https://m.media-amazon.com/images/I/81j7AVj8EKL._UY550_.jpg"],
    instructions:['Care Instructions: Machine Wash','Fit Type: Regular Fit','Soft & Breathable Cotton fabric','Regular collar long sleeve shirt','Single pocket at chest','Solid color','Pair it up with formal trousers for a sharp formal look','']
},
{
    name:"Women's Denim Jacket",
    brand:"FUN DAY FASHION STORE",
    rating:3,
    noOfRatings:443,
    price:349,
    off:83,
    gender:'female',
    category:'Jacket',
    season:'',
    loc:'',
    size:['s','m','l','xl','2xl','3xl'],
    color:["black","white","navy blue","maroon","Neon green","new dark blue","pista green","army green","cool blue"],
    images:["https://m.media-amazon.com/images/I/516sxnuIGyL._SY741._SX._UX._SY._UY_.jpg","https://m.media-amazon.com/images/I/516yGGy8nkL._SY741._SX._UX._SY._UY_.jpg","https://m.media-amazon.com/images/I/514Atpwtr2L._SY741._SX._UX._SY._UY_.jpg","https://m.media-amazon.com/images/I/71QXibwoySL._SY741._SX._UX._SY._UY_.jpg","https://m.media-amazon.com/images/I/51BRDIkfsKL._SY741._SX._UX._SY._UY_.jpg"],
    instructions:['Care Instructions: Machine Wash','Fit Type: Regular']
},
{
    name:"Round Neck Sweatshirt",
    brand:"LEOTUDE",
    rating:5,
    noOfRatings:121,
    price:494,
    off:69,
    gender:'female',
    category:'shirt',
    season:'',
    loc:'',
    size:['s','m','l','xl','2xl'],
    color:["Navy"],
    images:["https://m.media-amazon.com/images/I/61nIiTSG8VL._UY741_.jpg","https://m.media-amazon.com/images/I/61jxi5FPVeL._UY550_.jpg"],
    instructions:['Care Instructions: Hand Wash Only','Fit Type: Loose','Fabric: Loopknit','Neck: Round Neck','Pattern: Printed','Color: Navy','Fit: Boyfriend/Loose Fit']
},
{
    name:"Slim Fit Jeans",
    brand:"Levi's",
    rating:4,
    noOfRatings:412,
    price:1449,
    off:50,
    gender:'male',
    category:'Jeans',
    season:'',
    loc:'',
    size:['s','m','l','xl','2xl'],
    color:["black","grey"],
    images:["https://m.media-amazon.com/images/I/61squlDBu2L._UY879_.jpg","https://m.media-amazon.com/images/I/61MrU7BkyVL._UX569_.jpg","https://m.media-amazon.com/images/I/61mDbtMtnIL._UX569_.jpg","https://m.media-amazon.com/images/I/91PmyM9yXQL._UX569_.jpg","https://m.media-amazon.com/images/I/91hqPzdoclL._UX569_.jpg","https://m.media-amazon.com/images/I/71zuXt6J-PL._UX569_.jpg"],
    instructions:['Care Instructions: Machine Wash']
},
{
    name:"Red Tape Men Jeans",
    brand:"Red Tape",
    rating:4,
    noOfRatings:41,
    price:1011,
    off:76,
    gender:'female',
    category:'Jeans',
    season:'',
    loc:'',
    size:['s','m','l','xl','2xl'],
    color:["Dark blue"],
    images:["https://m.media-amazon.com/images/I/715WV-lOxdS._UY741_.jpg","https://m.media-amazon.com/images/I/71vVNwfs8sS._UY445_.jpg","https://m.media-amazon.com/images/I/710MBdXaPpS._UY445_.jpg","https://m.media-amazon.com/images/I/71BS4SK+6JS._UY445_.jpg","https://m.media-amazon.com/images/I/81uYkOdXcJS._UY445_.jpg","https://m.media-amazon.com/images/I/71BS4SK+6JS._UY445_.jpg"],
    instructions:['Care Instructions: Machine Wash','Fit Type: Skinny','Fabric : 98.25% Cotton, 1.75% Spandex, 10.5 Oz, Denim','Pattern : Solid Washed','Closure : Button, Fly : Zipper','Fit : Skinny','Occasion : Casual']
},
{
    name:" Kurta Pant Dupatta Set ",
    brand:"Stylum",
    rating:4,
    noOfRatings:9,
    price:959,
    off:74,
    gender:'female',
    category:'Kurta',
    season:'',
    loc:'',
    size:['s','m','l','xl','2xl'],
    color:["blue"],
    images:["https://m.media-amazon.com/images/I/71BfqmqkQtL._UY445_.jpg","https://m.media-amazon.com/images/I/61FdAjeUElL._UY445_.jpg","https://m.media-amazon.com/images/I/91FqR4MmHoL._UY445_.jpg","https://m.media-amazon.com/images/I/611+FOt520L._UY445_.jpg","https://m.media-amazon.com/images/I/71x+qVlsTfL._UY445_.jpg","https://m.media-amazon.com/images/I/710L5L58wiL._UY445_.jpg","https://m.media-amazon.com/images/I/61KtstpFe5L._UY445_.jpg"],
    instructions:['Care Instructions: Machine Wash','Fit Type: Regular:-Bandhej Printed Embroidered Anarkali Kurta with Solid Pant and Lehariya Dupatta',
'Kurta Material:- Rayon || Bottom Material:- Rayon || Dupatta Material:- Poly Chiffon',
'Package Contents :- 1 Kurta :: 1 Pant :: 1 Dupatta || Style &',' Pattern :- Bandhani::Embroidered::Embellished::Leheriya',
'Kurta Length:- 46" Inch|| Bottom Length:- 38" Inch || Dupatta Length:- 2.35 Mtr',
'Neck:- Round Neck || Sleeve:- 3/4 Sleeve']
},
{
    name:"Anarkali Embellished Kurta",
    brand:"Ishin",
    rating:4,
    noOfRatings:108,
    price:1403,
    off:72,
    gender:'female',
    category:'Kurta',
    season:'',
    loc:'',
    size:['s','m','l','xl','2xl'],
    color:["blue","Pink","red","red & orange","yellow"],
    images:["https://m.media-amazon.com/images/I/71p66iHujBL._UX522_.jpg","https://m.media-amazon.com/images/I/71kmZOjqisL._UX385_.jpg","https://m.media-amazon.com/images/I/81SDcCvVmGL._UX385_.jpg","https://m.media-amazon.com/images/I/71w7kH1Wv6L._UX385_.jpg","https://m.media-amazon.com/images/I/71v13I2i1dL._UX385_.jpg","https://m.media-amazon.com/images/I/71z4wrTiXxL._UX385_.jpg" ],
    instructions: ['Care Instructions:  Dry Clean Only','Fit Type:Regular,Pink Bandhani Embroidered Anarkali Kurta, has Round Neck, Three-Quarter Sleeves, Flared hem, has No Slits',
'Package Contents :- 1 Kurta ,The Garment Measurement of Small Size is 36" inches Which Fits to the Actual Body Bust of Size 34" inches Comfortably. The Same Criteria will Follow for Other Sizes Like Medium, Large, X-Large, XX-Large. We recommend you buy a size larger.','FITS ALL OCCASIONS: It makes a great addition to your wardrobe for festive wear, dailywear, casual wear, office wear or evening wear with its evergreen design also this Kurti makes it a Wonderful gifting package for any occasion. ','Ishin has many categories of women wear like Kurta Set , Kurta Palazzo set, Salwar suits , Kurta trouser set, Kurta Sharara set, Kurtas for Women, Trending Kurta For Women, Anarkali Kurtas, Bandhani Kurtas, Cotton Dress, Flared Dresses, Casual Wear, Party Outfit , Kaftan Dresses, Lurex Top, Cotton Top, Peplum TOP, Short Top. Casual Wear Sarees, Georgette Saree, Chiffon Sarees, Poly Silk Sarees, Art Silk Sarees, Festive Wear Sarees.']
},
{
name:"Wear Your Opinion Women's Premium Tie Dye Oversize Long Baggy Style Tshirt",
brand:"Wear Your Opinion",
rating:3,
noOfRatings:196,
price:599,
off:70,
gender:'female',
category:'shirt',
season:'',
loc:'',
size:['s','m','l','xl'],
color:["SoftPink","SoftOrange"],
images:["https://m.media-amazon.com/images/I/619WybjT4mL._UY445_.jpg","https://m.media-amazon.com/images/I/61+sm6ilDGL._UY445_.jpg","https://m.media-amazon.com/images/I/51nsoHA7ByL._UY445_.jpg","https://m.media-amazon.com/images/I/51CA9R50AKL._UY445_.jpg","https://m.media-amazon.com/images/I/71mNJduZA-L._UX342_.jpg"],
instructions:['Care Instructions: Machine Wash','Fit Type:loose fit','Size Chart: Please Refer The Size Chart available in Product Image. Available in the size S- 42, M-44, L-46, XL-48',
'Material: Crafted with a Proprietary Blend Of Premium Cotton, feels super soft on your skin.',
"Style: Oversized fit, street-style outfit. Team this with your favorite denims, or WYO's joggers with metal chains to give the very trendy street style look.",
'Sleeve & Neck: Round Neck, Sits just right. Drop shoulders that give a cooler laidback look.']
},
{
name:"Polo Shirt",
brand:"Van Heusen",
rating:4,
noOfRatings:30297,
price:589,
off:46,
gender:'male',
category:'Shirt',
season:'',
loc:'',
size:['s','m','l','xl','2xl'],
color:["red","black","white","blue"],
images:["https://m.media-amazon.com/images/I/71V4RsIUADL._SX342._SX._UX._SY._UY_.jpg","https://m.media-amazon.com/images/I/61r2oSzQCpL._SX342._SX._UX._SY._UY_.jpg","https://m.media-amazon.com/images/I/81kgwhaUNpL._SX342._SX._UX._SY._UY_.jpg","https://m.media-amazon.com/images/I/81hMVSZhT7L._SX342._SX._UX._SY._UY_.jpg","https://m.media-amazon.com/images/I/81IrnC1mk9L._SX342._SX._UX._SY._UY_.jpg"],
instructions:['Care Instructions: Machine Wash','Fit Type: Regular Fit','Occasion : Leisure Sport','Pattern : Solid','Fit :Regular Fit','Material: 60%Cotton40%Polyester','Sleeves : Half Sleeves']
},
{
name:"Lehenga choli",
brand:"Wommaniya Impex",
rating:4,
noOfRatings:68,
price:1169,
off:42,
gender:'Kids',
categoty:'Lehenga',
season:'',
loc:'',
size:['l','m','xl'],
color:["Green Rani","Red White"],
images:["https://m.media-amazon.com/images/I/61kA13RmfSL._UX466_.jpg","https://m.media-amazon.com/images/I/611a54LDAaL._UX466_.jpg","https://m.media-amazon.com/images/I/61ssmaMi5SL._UX679_.jpg"],
instructions:['Care Instructions: Dry Clean Only','It’s Ready to Wear Girls Party Wear Girls pattu pavadai jacquard silk Lehenga Choli.',
'Top (choli) made from art silk with embroidery N diamond work, Lehenga made from jacquard silk with designer finish lace, Inner fabric-Soft Cotton',
'Best Suitable For All Occasion Like Wedding, Ceremonial, Party, Birthday, Festival Etc',
'Disclaimer:- The images represent actual product though color of the image and product may slightly differ.']
},
{
name:"Regular T-Shirt",
brand:"Van Heusen",
rating:4,
noOfRatings:1450,
price:500,
off:50,
gender:'male',
category:'shirt',
season:'',
loc:'',
size:['s','m','l','xl','2xl'],
color:[" Multi - Pink","Multi - Blue","Multi - Grey","Multi - Black"],
images:["https://m.media-amazon.com/images/I/71qxaCOadvS._UX342_.jpg","https://m.media-amazon.com/images/I/81es0fU1nES._UX342_.jpg","https://m.media-amazon.com/images/I/61nRnXGSmgS._UX342_.jpg","https://m.media-amazon.com/images/I/81i5YrWozBS._UX342_.jpg"],
instructions:['Care Instructions: Machine Wash','Fit Type: Regular Fit','Van Heusen sport Tshirt','Material Composition: 100% Cotton; Lifestyle: Casual;','Material Type: Cotton; Color Name: Multi - Pink','Sleeve Type: Half Sleeve; Fit Type: Regular Fit; Sport Type','Outdoor Lifestyle']
},
{
name:"Kurta and Dhoti Pant Set",
brand:"JBN Creation",
rating:4.0,
noOfRatings:73,
price:562,
off:75,
gender:'Kids',
category:'Kurta',
season:'',
loc:'',
size:['l','m','xl'],
color:["Wine"],
images:["https://m.media-amazon.com/images/I/51oViSc5NOL._UY445_.jpg","https://m.media-amazon.com/images/I/513GSW7vD4L._UY550_.jpg",
"https://m.media-amazon.com/images/I/510lNTpXAIL._UL1440_.jpg","https://m.media-amazon.com/images/I/51GZraCmimL._UL1440_.jpg","https://m.media-amazon.com/images/I/81QVu25S9tL._UL1440_.jpg"],
instructions:['Care Instructions: Dry Clean Only','Fit type:Regular',
'Fabric: Cotton Silk Blend | Contents: Kurta and Dhoti Pant Set',
'Straight Kurta With Mandarin Collar And Button Closure Along With Versatile Cowl Dhoti To Look Your Dashing Best',
'We manufacture kids wear for boys 1-2 years, 2-3 years, 3-4 years, 4-5 years, 5-6 years, 6-7 years, 7-8 years, 8-9 years, 9-10 years, 10-11 years, 11-12 years, 12-13 years, 13-14 years, 14-15 years and kids wear for baby boys 0-6 months, 6-12 months, 12-18 months, 18-24 months.',
"All our kurtas, Sherwani, Indowestern and Nehru Jackets have loosening over the body measurement. Measurements shown in images or the size chart section are garment measurements, so take adequate 5-6 inches loosening over the little champion's body measurement to get the right fit. Our kurtas are Medium length and Regular Fit. Our Kurta fitting is usually slightly relaxed compared to a Regular Shirt's fitting. Select your Kurta size based on your chest dimension.','Save it for janmashtami dress for baby boy as well, just add a bansuri or a flute to make this a krishna dress for baby boy! These kids ethnic wear for boys under boys clothing are also used as pathani suit for boys stylish, jubba for boys, panjabi for boys or khan dress for boys stylish. The bottom is a patiala style cowl pattern draped dhoti pant. Most material used for kurta under 300 tensil count only.','Wash Care Instructions: Dry Clean preferably or cold light wash. Disclaimer: We have made a consistent effort to make the colors and finishes similar to the image of the products you see on screen. However, the actual product and the images on the website can differ! Customer's discretion is advised."]
},
{
    name:'kurta with dhoti ',
    brand:'Supermini',
    rating:4,
    noOfRatings:1502,
    price:475,
    off:66,
    gender:'boys',
    categoty:'ethnic wear',
    season:'',
    loc:'',
    size:['l','m','xl'],
    color:["yellow","white"],
    images:["https://m.media-amazon.com/images/I/71SSCX42hvL._UY879_.jpg","https://m.media-amazon.com/images/I/61e1o1QirHL._UX679_.jpg"],
    instructions:["Care Instructions: Hand Wash",'Fit Type: Regular','MATERIAL: Traditional Indian wear long Kurta made from 100% Cotton with golden thread work. The breathable fabric of these kurtas gets softer with every wash. Comes with easy elastic Dhoti and has colored stripe at front','STYLE: Regular Fit, Fits True to size, great fit and feel.','Please Note: Colours may slightly vary depending on your screen brightness.']
},
{
    name:'kurta and pyjama set ',
    brand:'AJ DEZINES',
    rating:4,
    noOfRatings:1604,
    price:824,
    off:73,
    gender:'boys',
    categoty:'ethnic wear',
    season:'',
    loc:'',
    size:['l','m','xl'],
    color:["blue"],
    images:["https://m.media-amazon.com/images/I/8117QsRutiL._UY879_.jpg","https://m.media-amazon.com/images/I/81Rxpb+jL8L._UY879_.jpg"],
    instructions:["Care Instructions: Hand Wash only",'Fit Type: Regular','MATERIAL: Traditional Indian wear Silk Cotton fabric for the most promising comfort','Sales Package-Kurta, Waistcoat and Breeches','STYLE: Regular Fit, Fits True to size, great fit and feel.','Please Note: Colours may slightly vary depending on your screen brightness.']
},
{
    name:'boys ethnic wear ',
    brand:'Pohar Creation',
    rating:4,
    noOfRatings:82,
    price:299,
    off:67,
    gender:'boys',
    categoty:'ethnic wear',
    season:'',
    loc:'',
    size:['l','m','xl'],
    color:["sky blue"],
    images:["https://m.media-amazon.com/images/I/71jLbchDkjL._UY879_.jpg","https://m.media-amazon.com/images/I/71jLbchDkjL._UY879_.jpg"],
    instructions:["Care Instructions: Dry Clean Only",'Fit Type: Regular','MATERIAL: Traditional Indian wear Silk Cotton fabric','Hand Picked Selection Kids Ethnic Wear for Boys','Please Note: Colours may slightly vary depending on your screen brightness.']
},
{
    name:'Kids Clan Cotton Shirt Dress ',
    brand:'Kids Clan',
    rating:3.9,
    noOfRatings:72,
    price:799,
    off:57,
    gender:'boys',
    categoty:'casual wear',
    season:'summer',
    loc:'',
    size:['l','m','xl'],
    color:["white","brown"],
    images:["https://m.media-amazon.com/images/I/61xeW6pBBgL._UX679_.jpg","https://m.media-amazon.com/images/I/51vdZtLQlZL._UX569_.jpg"],
    instructions:["Care Instructions: Machine wash",'Fit Type: Regular','MATERIAL:Cotton fabric','Please Note: Colours may slightly vary depending on your screen brightness.']
},
{
    name:'Cloth Bucket Lining Shirt ',
    brand:'Cloth Bucket',
    rating:3,
    noOfRatings:332,
    price:349,
    off:65,
    gender:'boys',
    categoty:'casual wear',
    season:'summer',
    loc:'',
    size:['l','m','xl'],
    color:["creamline"],
    images:["https://m.media-amazon.com/images/I/31-+zMEZ7eL.jpg","https://m.media-amazon.com/images/I/31cr+GxfBXL._UY500_.jpg"],
    instructions:["Care Instructions: Machine wash",'Fit Type: Regular,Full Sleeves','MATERIAL:Cotton fabric','Please Note: Colours may slightly vary depending on your screen brightness.']
},
{
    name:'Amazon Brand-Jam and Honey boys Shirt ',
    brand:'Jam and Honey',
    rating:4,
    noOfRatings:844,
    price:487,
    off:62,
    gender:'boys',
    categoty:'casual wear',
    season:'',
    loc:'',
    size:['l','m','xl'],
    color:["white and black"],
    images:["https://m.media-amazon.com/images/I/91VzCGOK3aL._UY550_.jpg","https://m.media-amazon.com/images/I/91M0HlSecqL._UY550_.jpg"],
    instructions:["Care Instructions: Machine wash",'Fit Type: Regular with all over print,half Sleeve','MATERIAL:100% Cotton fabric','Please Note: Colours may slightly vary depending on your screen brightness.']
},
{
    name:'Honey boys Shirt ',
    brand:'Jam and Honey',
    rating:4,
    noOfRatings:1973,
    price:489,
    off:69,
    gender:'boys',
    categoty:'casual wear',
    season:'',
    loc:'',
    size:['l','m','xl'],
    color:["Olive Green"],
    images:["https://m.media-amazon.com/images/I/81tNqEvMTwL._UY550_.jpg","https://m.media-amazon.com/images/I/81NhJY7vLOL._UY550_.jpg"],
    instructions:["Care Instructions: Machine wash",'Fit Type: Regular fit,half Sleeve','MATERIAL:100% Cotton fabric active colors and designs','Please Note: Colours may slightly vary depending on your screen brightness.']
},
{
    name:'Max boys kurta',
    brand:'Max',
    rating:5,
    noOfRatings:973,
    price:409,
    off:26,
    gender:'kids',
    categoty:'ethnic wear',
    season:'',
    loc:'',
    size:['l','m','xl'],
    color:["Cream"],
    images:["https://m.media-amazon.com/images/I/81i8sBpc3gL._UX679_.jpg","https://m.media-amazon.com/images/I/81i8sBpc3gL._UX679_.jpg"],
    instructions:["Care Instructions: Machine wash",'Fit Type: Regular fit,half Sleeve','MATERIAL: Cotton blend fabric','Please Note: Colours may slightly vary depending on your screen brightness.']
},
{
    name:' Prited Dress',
    brand:'Jwalin',
    rating:5,
    noOfRatings:78,
    price:799,
    off:68,
    gender:'female',
    categoty:'top',
    season:'',
    loc:'',
    size:['s','m','l'],
    color:["rama green"],
    images:["https://m.media-amazon.com/images/I/8151EfNw4QL._UY879_.jpg","https://m.media-amazon.com/images/I/81Ig289fq-L._UY879_.jpg"],
    instructions:["Care Instructions: Hand Wash Only",'Fit Type: Regular','Fabric: Crepe','Please Note: Colours may slightly vary depending on your screen brightness.','Wash Care: Cold Water Wash/ Do Not Iron on Print','Standard Sizing For Kids: 7to10 years Chest 32" & 10to13 years Chest 36" 13to16 years Chest 38"']

},
{
    name:'Adiva girls midi dress ',
    brand:'Adiva',
    rating:3.5,
    noOfRatings:20,
    price:399,
    off:80,
    gender:'kids',
    categoty:'skirt',
    season:'summer',
    loc:'',
    size:['12 months-18 months','18 months-24 months'],
    color:["blue"],
    images:["https://m.media-amazon.com/images/I/51R8dXRm6BL._UX679_.jpg","https://m.media-amazon.com/images/I/51Ec-N5ZlOL._UX679_.jpg"],
    instructions:["Care Instructions: Hand Wash Only",'Fit Type: Regular','Fabric: jeans','Please Note: Colours may slightly vary depending on your screen brightness.','Wash Care: Cold Water Wash']
},
{
    name:'Naughty Ninos girls Pinafore',
    brand:'Naughty Ninos',
    rating:4,
    noOfRatings:142,
    price:659,
    off:61,
    gender:'kids',
    categoty:'skirt',
    season:'summer',
    loc:'',
    size:['l','m','xl'],
    color:["peachy pink"],
    images:["https://m.media-amazon.com/images/I/51iVofb1R5L._UY879_.jpg","https://m.media-amazon.com/images/I/51SmqvCmo2L._UY879_.jpg"],
    instructions:["Care Instructions: Machine Wash",'Fit Type: Regular','Fabric: 100% cotton dress,inside vest made with soft strethable cotton fabric and front chest embroidred ','Please Note: Colours may slightly vary depending on your screen brightness.']
},
{
    name:'Wish Karo girls A-line knee length dress ',
    brand:'Wish Karo',
    rating:4,
    noOfRatings:237,
    price:569,
    off:72,
    gender:'female',
    categoty:'dress',
    season:'',
    loc:'',
    size:['l','m','xl'],
    color:["multicolor"],
    images:["https://m.media-amazon.com/images/I/51F0749owGL._UY879_.jpg","https://m.media-amazon.com/images/I/51deiWXhY2L._UY879_.jpg"],
    instructions:["Care Instructions: Dry Clean Only",'Fit Type: Regular','Fabric: net ','Style:A-line','Pattern: PLain/Solid','Please Note: Colours may slightly vary depending on your screen brightness.']
},
{
    name:'OMLI girls Midi Dress ',
    brand:'OMLI',
    rating:3,
    noOfRatings:235,
    price:398,
    off:60,
    gender:'kids',
    categoty:'frock',
    season:'',
    loc:'',
    size:['l','m','xl'],
    color:["grey","pink"],
    images:["https://m.media-amazon.com/images/I/71ymXjmTXPL._UX679_.jpg","https://m.media-amazon.com/images/I/717T8ee2dnL._UX679_.jpg"],
    instructions:["Care Instructions: Hand Wash Only",'Fit Type: Regular','Fabric: net ','Pattern: PLain/Solid','Material Composition: Satin Blend','Please Note: Colours may slightly vary depending on your screen brightness.']
},
{
    name:'Zolario 3 piece Boys suit ',
    brand:'Zolario',
    rating:4,
    noOfRatings:666,
    price:945,
    off:53,
    gender:'kids',
    categoty:'suit',
    season:'',
    loc:'',
    size:['l','m','xl'],
    color:["grey","black"],
    images:["https://m.media-amazon.com/images/I/61Bs8dETthL._UX679_.jpg","https://m.media-amazon.com/images/I/71ba3+VZa5L._UX679_.jpg"],
    instructions:["Care Instructions: Machine Wash",'Fit Type: Regular','Fabric: net ','IMPORTANT: Latest Designer, Regular Size, Fine Printed, Good Quality Material','Please Note: Colours may slightly vary depending on your screen brightness.']
},
{
    name:'Doodle girls dresses ',
    brand:'Doodle',
    rating:4,
    noOfRatings:269,
    price:879,
    off:45,
    gender:'kids',
    categoty:'dress',
    season:'summer',
    loc:'',
    size:['l','m','xl'],
    color:["pink"],
    images:["https://m.media-amazon.com/images/I/517SpI6jE1L._UX679_.jpg","https://m.media-amazon.com/images/I/51wHBB9ApIL._UX679_.jpg"],
    instructions:["Care Instructions: Machine Wash",'Fit Type: Regular','Material Quality: Its Made Of Soft Material. Skin Friendly Material, Which Is Gentle On Childs Sensitive Skin.','Sleeve Type: Sleeveless; Material Composition: Satin','Please Note: Colours may slightly vary depending on your screen brightness.']
},
{
    name:'Superminis boys cotton kurta with dhoti ',
    brand:'Supermini',
    rating:4,
    noOfRatings:1502,
    price:475,
    off:66,
    gender:'kids',
    categoty:'ethnic wear',
    season:'',
    loc:'',
    size:['l','m','xl'],
    color:["yellow and white"],
    images:["https://m.media-amazon.com/images/I/71SSCX42hvL._UY879_.jpg","https://m.media-amazon.com/images/I/61e1o1QirHL._UX679_.jpg"],
    instructions:["Care Instructions: Hand Wash",'Fit Type: Regular','MATERIAL: Traditional Indian wear long Kurta made from 100% Cotton with golden thread work. The breathable fabric of these kurtas gets softer with every wash. Comes with easy elastic Dhoti and has colored stripe at front','STYLE: Regular Fit, Fits True to size, great fit and feel.','Please Note: Colours may slightly vary depending on your screen brightness.']
},
{
    name:'AJ DEZINES Boys silk cotton kurta and pyjama set ',
    brand:'AJ DEZINES',
    rating:4,
    noOfRatings:1604,
    price:824,
    off:73,
    gender:'kids',
    categoty:'ethnic wear',
    season:'',
    loc:'',
    size:['l','m','xl'],
    color:["blue"],
    images:["https://m.media-amazon.com/images/I/8117QsRutiL._UY879_.jpg","https://m.media-amazon.com/images/I/81Rxpb+jL8L._UY879_.jpg"],
    instructions:["Care Instructions: Hand Wash only",'Fit Type: Regular','MATERIAL: Traditional Indian wear Silk Cotton fabric for the most promising comfort','Sales Package-Kurta, Waistcoat and Breeches','STYLE: Regular Fit, Fits True to size, great fit and feel.','Please Note: Colours may slightly vary depending on your screen brightness.']
},
{
    name:'Pohar creation boys ethnic wear ',
    brand:'Pohar Creation',
    rating:4,
    noOfRatings:82,
    price:299,
    off:67,
    gender:'men',
    categoty:'ethnic wear',
    season:'',
    loc:'',
    size:['l','m','xl'],
    color:["sky blue"],
    images:["https://m.media-amazon.com/images/I/71jLbchDkjL._UY879_.jpg","https://m.media-amazon.com/images/I/71jLbchDkjL._UY879_.jpg"],
    instructions:["Care Instructions: Dry Clean Only",'Fit Type: Regular','MATERIAL: Traditional Indian wear Silk Cotton fabric','Hand Picked Selection Kids Ethnic Wear for Boys','Please Note: Colours may slightly vary depending on your screen brightness.']
},
{
    name:'Kids Clan Cotton Shirt Dress ',
    brand:'Kids Clan',
    rating:4,
    noOfRatings:72,
    price:799,
    off:57,
    gender:'kids',
    categoty:'casual',
    season:'summer',
    loc:'',
    size:['l','m','xl'],
    color:["white","brown"],
    images:["https://m.media-amazon.com/images/I/61xeW6pBBgL._UX679_.jpg","https://m.media-amazon.com/images/I/51vdZtLQlZL._UX569_.jpg"],
    instructions:["Care Instructions: Machine wash",'Fit Type: Regular','MATERIAL:Cotton fabric','Please Note: Colours may slightly vary depending on your screen brightness.']
},
{
    name:'Lining Shirt ',
    brand:'Cloth Bucket',
    rating:3.4,
    noOfRatings:332,
    price:349,
    off:65,
    gender:'kids',
    categoty:'casual wear',
    season:'summer',
    loc:'',
    size:['l','m','xl'],
    color:["creamline"],
    images:["https://m.media-amazon.com/images/I/31-+zMEZ7eL.jpg","https://m.media-amazon.com/images/I/31cr+GxfBXL._UY500_.jpg"],
    instructions:["Care Instructions: Machine wash",'Fit Type: Regular,Full Sleeves','MATERIAL:Cotton fabric','Please Note: Colours may slightly vary depending on your screen brightness.']
},
{
    name:'Amazon Brand-Jam and Honey boys Shirt ',
    brand:'Jam and Honey',
    rating:4.2,
    noOfRatings:844,
    price:487,
    off:62,
    gender:'kids',
    categoty:'casual',
    season:'',
    loc:'',
    size:['l','m','xl'],
    color:["white and black"],
    images:["https://m.media-amazon.com/images/I/91VzCGOK3aL._UY550_.jpg","https://m.media-amazon.com/images/I/91M0HlSecqL._UY550_.jpg"],
    instructions:["Care Instructions: Machine wash",'Fit Type: Regular with all over print,half Sleeve','MATERIAL:100% Cotton fabric','Please Note: Colours may slightly vary depending on your screen brightness.']
},
{
    name:'Kidsville Mickey & Friends Printed Sweatshirt for kids',
    brand:'Kidsville',
    rating:4,
    noOfRatings:10,
    price:639,
    off:60,
    gender:'kids',
    categoty:'shirt',
    season:'winter',
    loc:'',
    size:['xs','s'],
    color:["candy pink"],
    images:["https://m.media-amazon.com/images/I/61GK5xzyE-L._UX679_.jpg","https://m.media-amazon.com/images/I/610Lkt+i75L._UX679_.jpg"],
    instructions:["Care Instructions: Hand Wash","CottonPattern : Solid"] 
},




{
    name:'MINI KLUB Baby Bodysuit',
    brand:'MINI KLUB',
    rating:4,
    noOfRatings:10,
    price:289,
    off:60,
    gender:'kids',
    categoty:'Bodysuit',
    season:'',
    loc:'',
    size:['l','m','xl'],
    color:["Multi1"],
    images:["https://m.media-amazon.com/images/I/51CDrhRG1GL._UX679_.jpg","https://m.media-amazon.com/images/I/61ZNygFRo-L._UL1200_.jpg",'https://m.media-amazon.com/images/I/61wGFFU5sAL._UL1200_.jpg'],
    instructions:["Care Instructions: Machine Wash","Fit Type: regular fit","Color Name: Multi100% Cotton"]
},
{
    name:'U.S. POLO ASSN. Regallo Skinny Fit Mid Rise Jeans',
    brand:'U.S. POLO ASSN',
    rating:4,
    noOfRatings:9,
    price:1099,
    off:50,
    gender:'male',
    categoty:'Skinny Fit Mid Rise Jeans',
    season:'',
    loc:'',
    size:['l','m','xl'],
    color:["blue"],
    images:["https://m.media-amazon.com/images/I/712OpIyJJgL._UX569_.jpg","https://m.media-amazon.com/images/I/91s0czrT7qL._UX569_.jpg",'https://m.media-amazon.com/images/I/719LX3TzyFL._UX569_.jpg'],
    instructions:["Care Instructions: Machine Wash","Fit Type: Regular","Mid-rise waist","Button with zip fly closure","Five pockets","Stonewashed"]
},

{
    name:'Amazon Brand-Jam and Honey boys Shirt ',
    brand:'Jam and Honey',
    rating:4.1,
    noOfRatings:1973,
    price:489,
    off:69,
    gender:'boys',
    categoty:'casual wear',
    season:'',
    loc:'',
    size:['8-9 years','9-10 years','10-11 years'],
    color:["Olive Green"],
    images:["https://m.media-amazon.com/images/I/81tNqEvMTwL._UY550_.jpg","https://m.media-amazon.com/images/I/81NhJY7vLOL._UY550_.jpg"],
    instructions:["Care Instructions: Machine wash",'Fit Type: Regular fit,half Sleeve','MATERIAL:100% Cotton fabric active colors and designs','Please Note: Colours may slightly vary depending on your screen brightness.']
},
{
    name:'casual shirt',
    brand:'Max',
    rating:4.0,
    noOfRatings:990,
    price:355,
    off:21,
    gender:'boys',
    categoty:'casual',
    season:'',
    loc:'',
    size:['x','l','xl'],
    color:["Sky blue"],
    images:["https://m.media-amazon.com/images/I/81Y9u6KFAoL._UX569_.jpg","https://m.media-amazon.com/images/I/81BK-xFYCmL._UX569_.jpg"],
    instructions:["Care Instructions: Machine wash",'Fit Type: Regular fit','MATERIAL:100% Cotton fabric','Please Note: Colours may slightly vary depending on your screen brightness.']

},
{
    name:'U.S POLO ASSN.boys T-shirt',
    brand:'U.S POLO ASSN.',
    rating:4.0,
    noOfRatings:274,
    price:379,
    off:24,
    gender:'male',
    categoty:'casual',
    season:'',
    loc:'',
    size:['x','l','xl'],
    color:["yellow"],
    images:["https://m.media-amazon.com/images/I/51lSJ4kHnAL._UX679_.jpg","https://m.media-amazon.com/images/I/51uz1pUx1eL._UX569_.jpg"],
    instructions:["Care Instructions: Machine wash",'Fit Type: Regular fit,Half Sleeve Crew Neck Tshirt with contrast thread color at shoulder and bottom hem, contrast branding at chest and dual color print at back. Neck finishing with spandex rib for better fit & comfort','MATERIAL:100% Cotton fabric','Please Note: Colours may slightly vary depending on your screen brightness.']

},
{
    name:'Max boys kurta',
    brand:'Max',
    rating:4.9,
    noOfRatings:973,
    price:409,
    off:26,
    gender:'kids',
    categoty:'ethnic wear',
    season:'',
    loc:'',
    size:['x','l','xl'],
    color:["Cream"],
    images:["https://m.media-amazon.com/images/I/81i8sBpc3gL._UX679_.jpg","https://m.media-amazon.com/images/I/81i8sBpc3gL._UX679_.jpg"],
    instructions:["Care Instructions: Machine wash",'Fit Type: Regular fit,half Sleeve','MATERIAL: Cotton blend fabric','Please Note: Colours may slightly vary depending on your screen brightness.']
},
{
    name:'Allen Solly Junior boys shirt',
    brand:'Allen Solly Junior',
    rating:4,
    noOfRatings:2246,
    price:619,
    off:61,
    gender:'kids',
    categoty:'casual',
    season:'',
    loc:'',
    size:['9-10 years','10-11 years','11-12 years','12-13 years','13-14 years'],
    color:["Red and blue"],
    images:["https://m.media-amazon.com/images/I/91xljh1pU6L._UX679_.jpg","https://m.media-amazon.com/images/I/91l1uPSICfL._UX569_.jpg"],
    instructions:["Care Instructions: Machine wash",'Fit Type: Regular fit','MATERIAL:100% Cotton fabric','Pattern:Check','Please Note: Colours may slightly vary depending on your screen brightness.']
},
{
    name:'boys Shirt ',
    brand:'Jam and Honey',
    rating:4,
    noOfRatings:13,
    price:512,
    off:70,
    gender:'kids',
    categoty:'casual',
    season:'',
    loc:'',
    size:['x','l','xl'],
    color:["Pink"],
    images:["https://m.media-amazon.com/images/I/51TlhUKxqCL._UX679_.jpg","https://m.media-amazon.com/images/I/51vmKuAX4hL._UX569_.jpg"],
    instructions:["Care Instructions: Machine wash",'Fit Type: Regular fit,half Sleeve','MATERIAL:100% Cotton fabric active colors and designs','Please Note: Colours may slightly vary depending on your screen brightness.']
},
{
    name:'Giny and jony Boys shirt ',
    brand:'Giny & Jony',
    rating:4,
    noOfRatings:667,
    price:603,
    off:47,
    gender:'kids',
    categoty:'casual',
    season:'',
    loc:'',
    size:['x','l','xl'],
    color:["Blue and balck"],
    images:["https://m.media-amazon.com/images/I/51TlhUKxqCL._UX679_.jpg","https://m.media-amazon.com/images/I/51vmKuAX4hL._UX569_.jpg"],
    instructions:["Care Instructions: Machine wash",'Fit Type: Regular fit,full Sleeve','MATERIAL:100% Cotton fabric','Please Note: Colours may slightly vary depending on your screen brightness.']
},

{
    name:'Diverse boys slim fit shirt',
    brand:'Diverse',
    rating:3,
    noOfRatings:191,
    price:359,
    off:72,
    gender:'kids',
    categoty:'casual',
    season:'',
    loc:'',
    size:['x','l','xl'],
    color:["beige and brown"],
    images:["https://m.media-amazon.com/images/I/71yLkuTeWJL._UX679_.jpg","https://m.media-amazon.com/images/I/71NOzIyYS+L._UX679_.jpg"],
    instructions:["Care Instructions: Machine wash",'Fit Type: Slim fit','MATERIAL:Beautifully crafted in Cotton linen, it comes in a convenient slim fit and the soft fabric of this garment helps your kid feel utterly comfortable.','Please Note: Colours may slightly vary depending on your screen brightness.']
},
{
    name:'Junior boys shirt',
    brand:'Allen Solly Junior',
    rating:4,
    noOfRatings:2246,
    price:619,
    off:61,
    gender:'kids',
    categoty:'casual',
    season:'',
    loc:'',
    size:['x','l','xl'],
    color:["Red and blue"],
    images:["https://m.media-amazon.com/images/I/91xljh1pU6L._UX679_.jpg","https://m.media-amazon.com/images/I/91l1uPSICfL._UX569_.jpg"],
    instructions:["Care Instructions: Machine wash",'Fit Type: Regular fit','MATERIAL:100% Cotton fabric','Pattern:Check','Please Note: Colours may slightly vary depending on your screen brightness.']
},
{
    name:'Honey boys Shirt ',
    brand:'Jam and Honey',
    rating:3,
    noOfRatings:13,
    price:512,
    off:70,
    gender:'kids',
    categoty:'casual',
    season:'',
    loc:'',
    size:['x','l','xl'],
    color:["Pink"],
    images:["https://m.media-amazon.com/images/I/51TlhUKxqCL._UX679_.jpg","https://m.media-amazon.com/images/I/51vmKuAX4hL._UX569_.jpg"],
    instructions:["Care Instructions: Machine wash",'Fit Type: Regular fit,half Sleeve','MATERIAL:100% Cotton fabric active colors and designs','Please Note: Colours may slightly vary depending on your screen brightness.']
},
{
    name:'Boys shirt ',
    brand:'Giny & Jony',
    rating:3,
    noOfRatings:667,
    price:603,
    off:47,
    gender:'kids',
    categoty:'casual',
    season:'',
    loc:'',
    size:['x','l','xl'],
    color:["Blue","balck"],
    images:["https://m.media-amazon.com/images/I/51TlhUKxqCL._UX679_.jpg","https://m.media-amazon.com/images/I/51vmKuAX4hL._UX569_.jpg"],
    instructions:["Care Instructions: Machine wash",'Fit Type: Regular fit,full Sleeve','MATERIAL:100% Cotton fabric','Please Note: Colours may slightly vary depending on your screen brightness.']
},
{
    name:'casual shirt',
    brand:'Max',
    rating:4,
    noOfRatings:990,
    price:355,
    off:21,
    gender:'kids',
    categoty:'casual',
    season:'',
    loc:'',
    size:['x','l','xl'],
    color:["Sky blue"],
    images:["https://m.media-amazon.com/images/I/81Y9u6KFAoL._UX569_.jpg","https://m.media-amazon.com/images/I/81BK-xFYCmL._UX569_.jpg"],
    instructions:["Care Instructions: Machine wash",'Fit Type: Regular fit','MATERIAL:100% Cotton fabric','Please Note: Colours may slightly vary depending on your screen brightness.']

},
{
    name:'U.S POLO T-shirt',
    brand:'U.S POLO ASSN.',
    rating:4.0,
    noOfRatings:274,
    price:379,
    off:24,
    gender:'male',
    categoty:'casual',
    season:'',
    loc:'',
    size:['x','l'],
    color:["yellow"],
    images:["https://m.media-amazon.com/images/I/51lSJ4kHnAL._UX679_.jpg","https://m.media-amazon.com/images/I/51uz1pUx1eL._UX569_.jpg"],
    instructions:["Care Instructions: Machine wash",'Fit Type: Regular fit,Half Sleeve Crew Neck Tshirt with contrast thread color at shoulder and bottom hem, contrast branding at chest and dual color print at back. Neck finishing with spandex rib for better fit & comfort','MATERIAL:100% Cotton fabric','Please Note: Colours may slightly vary depending on your screen brightness.']

},
{
    name:'Diverse boys slim fit shirt',
    brand:'Diverse',
    rating:3,
    noOfRatings:191,
    price:359,
    off:72,
    gender:'male',
    categoty:'casual',
    season:'',
    loc:'',
    size:['x','l','xl'],
    color:["beige and brown"],
    images:["https://m.media-amazon.com/images/I/71yLkuTeWJL._UX679_.jpg","https://m.media-amazon.com/images/I/71NOzIyYS+L._UX679_.jpg"],
    instructions:["Care Instructions: Machine wash",'Fit Type: Slim fit','MATERIAL:Beautifully crafted in Cotton linen, it comes in a convenient slim fit and the soft fabric of this garment helps your kid feel utterly comfortable.','Please Note: Colours may slightly vary depending on your screen brightness.']
},
]