export const PoductsList = [
    {
        name:'RCB Cricket Jersey 2023-24 -(Mens & Kids) Cricket',
        brand:'jusball',
        rating:4,
        noOfRatings:67,
        price:229,
        off:77,
        gender:'',
        categoty:'jersey',
        season:'',
        loc:'',
        size:['s','m','l','xl','2xl'],
        color:["red","black"],
        images:["https://m.media-amazon.com/images/I/51F+JsBaS9L._UX679_.jpg","https://m.media-amazon.com/images/I/51-NOmRmmDL._UX679_.jpg"],
        instructions:["Care Instructions: Machine Wash",'Fit Type: Slim Fit','Material: 100% Polyester','Care Instructions: Hand Wash Only','Please Note: Colours may slightly vary depending on your screen brightness.','Standard Sizing For Kids: 7to10 years Chest 32" & 10to13 years Chest 36" 13to16 years Chest 38"','Standard Sizing For Mens: Small Chest 36" & Medium Chest 38" Large Chest 40" X-Large Chest 42" XX-Large Chest 44"']
    },
    {
        name:'Puma Men T-Shirt',
        brand:'puma',
        rating:5,
        noOfRatings:10,
        price:329,
        off:70,
        gender:'male',
        categoty:'t-shirt',
        season:'',
        loc:'',
        size:['s','m','l'],
        color:["white","black"],
        images:["https://m.media-amazon.com/images/I/5183oPzSqSL._UX679_.jpg","https://m.media-amazon.com/images/I/51nmHE5Nk+L._UX466_.jpg",'https://m.media-amazon.com/images/I/51pxHn16vAL._UX466_.jpg','https://m.media-amazon.com/images/I/41AUMQrhVBL._UX466_.jpg','https://m.media-amazon.com/images/I/51pSrNYBGnL._UX466_.jpg'],
        instructions:["Care Instructions: Machine Wash",'Fit Type: Regular Fit','Style Name:-Tee','Model Name:-Logo Box Tee','Please Note: Colours may slightly vary depending on your screen brightness.','Brand Color:-Cotton Black','Activity Group:-Sport Classics']
    },
    {
        name:' Chikankari Linen Sarees',
        brand:'SWORNOF',
        rating:4,
        noOfRatings:1268,
        price:949,
        off:73,
        gender:'female',
        categoty:'saree',
        season:'',
        loc:'',
        size:[],
        color:["blue","grey","pink","orange"],
        images:["https://m.media-amazon.com/images/I/41uF1XPtd0L.jpg","https://m.media-amazon.com/images/I/81rOL+EMAaS._UX522_.jpg",'https://m.media-amazon.com/images/I/918o1N31c1S._UY500_.jpg',"https://m.media-amazon.com/images/I/61lZ7KOyYsL._SY679._SX._UX._SY._UY_.jpg","https://m.media-amazon.com/images/I/81P285LyhiL._SY500._SX._UX._SY._UY_.jpg","https://m.media-amazon.com/images/I/81hHNG3Z8GL._SY500._SX._UX._SY._UY_.jpg"],
        instructions:['Care Instructions: Machine Wash','Material : Soft Cotton','Design : Lucknowi Chikankari Hand Weaving Work','Style : The Texture And Weight Of The Saree Brings Image Prints One Step Closer To The Originals And Invites Attention','Occasion : Sarees for women, festive, traditional saree. Best birth-day gift for your loved ones. Each piece is elegantly crafted and will surely add to your wardrobe']
    },
    
    {
        name:' Floral Printed Saree',
        brand:'Kanishka',
        rating:3,
        noOfRatings:268,
        price:749,
        off:69,
        gender:'female',
        categoty:'saree',
        season:'',
        loc:'',
        size:[],
        color:["light purple","grey","pink","orange","yellow"],
        images:["https://m.media-amazon.com/images/I/31V4WIcT3fL._UY606_.jpg","https://m.media-amazon.com/images/I/41CVa8NcgoL._SY500._SX._UX._SY._UY_.jpg",'https://m.media-amazon.com/images/I/31g-DtZNotL._SY500._SX._UX._SY._UY_.jpg',"https://m.media-amazon.com/images/I/61lZ7KOyYsL._SY679._SX._UX._SY._UY_.jpg","https://m.media-amazon.com/images/I/41PR36BzFZL._SY500._SX._UX._SY._UY_.jpg","https://m.media-amazon.com/images/I/3128a28YDkL._SY500._SX._UX._SY._UY_.jpg"],
        instructions:['Care Instructions: Dry Clean Only','Material : Soft Cotton','Design : Lucknowi Chikankari Hand Weaving Work','Style : The Texture And Weight Of The Saree Brings Image Prints One Step Closer To The Originals And Invites Attention','Occasion : Sarees for women, festive, traditional saree. Best birth-day gift for your loved ones. Each piece is elegantly crafted and will surely add to your wardrobe']
    },

    {
        name:' Lycra Crop Top',
        brand:'siril',
        rating:5,
        noOfRatings:368,
        price:259,
        off:78,
        gender:'female',
        categoty:'top',
        season:'',
        loc:'',
        size:['s','l','m','xl'],
        color:["lpista green","grey","pink","orange","yellow","red","blue"],
        images:["https://m.media-amazon.com/images/I/61yfZiZJ7kL._UY445_.jpg","https://m.media-amazon.com/images/I/61GRfSyvOJL._SY445._SX._UX._SY._UY_.jpg",'https://m.media-amazon.com/images/I/51Hx9y2YCSL._SY445._SX._UX._SY._UY_.jpg',"https://m.media-amazon.com/images/I/61lZ7KOyYsL._SY679._SX._UX._SY._UY_.jpg","https://m.media-amazon.com/images/I/61A65-9usrL._SY445._SX._UX._SY._UY_.jpg","https://m.media-amazon.com/images/I/61ITGFcSvaL._SY445._SX._UX._SY._UY_.jpg"],
        instructions:['Care Instructions:Machine Wash','Fit Type: Regular Fit','Fabric : Lycra ','Style: Crop Half Sleeve Shirt || Work: Knitted, Solid','Neck Style : Collared Neck','Length : 14.5Inch|Bust Size : 33Inch. Please select size from the filter box and refer the size chart']
    },
    {
        name:' OOMPH! Crop Tops ',
        brand:'OOMPH!',
        rating:5,
        noOfRatings:368,
        price:199,
        off:78,
        gender:'female',
        categoty:'top',
        season:'',
        loc:'',
        size:['xs','s','l','m','xl'],
        color:["lpista green","grey","pink","orange","yellow","red","blue"],
        images:["https://m.media-amazon.com/images/I/61mRaOXVHUL._UY445_.jpg","https://m.media-amazon.com/images/I/618BYh7hVCL._UY445_.jpg",'https://m.media-amazon.com/images/I/61lc96aFQlL._UY445_.jpg',"https://m.media-amazon.com/images/I/61lZ7KOyYsL._SY679._SX._UX._SY._UY_.jpg","https://m.media-amazon.com/images/I/71nKg9a0xRL._UY445_.jpg","https://m.media-amazon.com/images/I/51s90e8NpKL._UY445_.jpg"],
        instructions:['Care Instructions:Machine Wash','Fit Type: Regular Fit','Fabric : Lycra ','Style: Crop Half Sleeve Shirt || Work: Knitted, Solid','Neck Style : Collared Neck','Length : 14.5Inch|Bust Size : 33Inch. Please select size from the filter box and refer the size chart','Suitable for women tops, top for women, tops, tops for women, women tops western latest, top, tops for women stylish latest, women top, jeans tops for women, tunic tops for women, top for women stylish, tops for girls, stylish tops for women, tunics for women stylish western, jeans tops for women stylish, casual tops for women, womens top, girls top, womens tops latest fashion, ladies top, tops women, top for women stylish western']
    },
    {
        name:' Cotton Straight Top',
        brand:'Yash Gallery ',
        rating:5,
        noOfRatings:448,
        price:199,
        off:78,
        gender:'female',
        categoty:'top',
        season:'',
        loc:'',
        size:['xs','s','l','m','xl'],
        color:["lemon green","yellow","red"],
        images:["https://m.media-amazon.com/images/I/71Xj7h0zOkL._UY445_.jpg","https://m.media-amazon.com/images/I/61wxq7ERzcL._SY445._SX._UX._SY._UY_.jpg",'https://m.media-amazon.com/images/I/71KgYt8vV7L._SX385._SX._UX._SY._UY_.jpg'],
        instructions:['Care Instructions:Machine Wash','Fit Type: Regular Fit','Fabric : Lycra ','Style: Crop Half Sleeve Shirt || Work: Knitted, Solid','Neck Style : Collared Neck','Length : 14.5Inch|Bust Size : 33Inch. Please select size from the filter box and refer the size chart','Suitable for women tops, top for women, tops, tops for women, women tops western latest, top, tops for women stylish latest, women top, jeans tops for women, tunic tops for women, top for women stylish, tops for girls, stylish tops for women, tunics for women stylish western, jeans tops for women stylish, casual tops for women, womens top, girls top, womens tops latest fashion, ladies top, tops women, top for women stylish western']
    },
    {
        name:' Cotton Straight Top',
        brand:'Yash Gallery ',
        rating:5,
        noOfRatings:448,
        price:199,
        off:58,
        gender:'female',
        categoty:'top',
        season:'',
        loc:'',
        size:['xs','s','l','m','xl'],
        color:["off-white",],
        images:["https://m.media-amazon.com/images/I/81U1JyVPkcL._UY445_.jpg","https://m.media-amazon.com/images/I/71whSNGJ40L._UY445_.jpg",'https://m.media-amazon.com/images/I/813i+2ZruXL._UY445_.jpg'],
        instructions:['Care Instructions:Machine Wash','Fit Type: Regular Fit','Fabric :cotton ','Style: Crop Sleeve Shirt || Work: Knitted, Solid','Neck Style : Collared Neck','Length : 14.5Inch|Bust Size : 33Inch. Please select size from the filter box and refer the size chart',]
    },
    {
        name:' Waistband Wide Jeans',
        brand:'AKA CHIC ',
        rating:4,
        noOfRatings:1448,
        price:899,
        off:78,
        gender:'female',
        categoty:'jeans',
        season:'',
        loc:'',
        size:['l','xl'],
        color:["off-white",],
        images:["https://m.media-amazon.com/images/I/71PjLhe-PSL._UX679_.jpg","https://m.media-amazon.com/images/I/71Ga8ur+qyL._UX679_.jpg",'https://m.media-amazon.com/images/I/71Kc-1xKgAL._UX679_.jpg','https://m.media-amazon.com/images/I/A1PKeikaXVL._UX679_.jpg'],
        instructions:['Care Instructions:Machine Wash','Fit Type: Regular Fit','Fabric :cotton ','High Rise','Wide Leg','To choose the right size- please refer Wide Leg size chart and how to measure image','Elasticated Waistband']
    },
    {
        name:' Women Jeans',
        brand:'AKA CHIC ',
        rating:3,
        noOfRatings:1448,
        price:1099,
        off:65,
        gender:'female',
        categoty:'jeans',
        season:'',
        loc:'',
        size:['l','xl','xxl','xxxl'],
        color:["pink","blue","beige"],
        images:["https://m.media-amazon.com/images/I/51bmHRHla6L._UY606_.jpg","https://m.media-amazon.com/images/I/510OnIFTWjL._UY606_.jpg",'https://m.media-amazon.com/images/I/81n+wBWBPTL._SX466._SX._UX._SY._UY_.jpg','https://m.media-amazon.com/images/I/811Yj8IY4JL._SX466._SX._UX._SY._UY_.jpg','https://m.media-amazon.com/images/I/51ifzItB9-L._SY606._SX._UX._SY._UY_.jpg','https://m.media-amazon.com/images/I/51x1CiG4NyL._SY606._SX._UX._SY._UY_.jpg'],
        instructions:['Care Instructions:Machine Wash','Fit Type: Regular Fit','Fabric :cotton ','High Rise','Wide Leg','To choose the right size- please refer Wide Leg size chart and how to measure image','Elasticated Waistband','Zip Fly With 2 Button Closure Elasticated Waistband']
    },
    {
        name:'Regular Fit Cigarette Pant',
        brand:'FASHION GALLERY',
        rating:4,
        noOfRatings:1448,
        price:299,
        off:50,
        gender:'female',
        categoty:'jeans',
        season:'',
        loc:'',
        size:['l'],
        color:["white"],
        images:["https://m.media-amazon.com/images/I/41X99kvhl6L._UY550_.jpg","https://m.media-amazon.com/images/I/31d49AzszNL._UY550_.jpg",],
        instructions:['Care Instructions:Machine Wash','Fit Type: Regular Fit','Fabric :cotton ','High Rise','Wide Leg','To choose the right size- please refer Wide Leg size chart and how to measure image','Elasticated Waistband','Zip Fly With 2 Button Closure Elasticated Waistband','Clouser type : 2" inch Standard Elasticated waist band for smooth grip of waist.The Cigarette Pant has Stratechable Fabric Which Gives All Around Comfort. The Cigarette Pant has interlock inside part and colour of variation available for Pant. This Cigarette Pant has Heavy and smooth Elastic material used in waist part which is very smooth and long lasting.The Fabric of Cigarette Pant is Premium quality Rayon Slub which is Skin Friendly & comfortable.']
    },
    {
        name:' Skinny Fit High Rise Jeans',
        brand:'Miss Chase',
        rating:3,
        noOfRatings:748,
        price:799,
        off:62,
        gender:'female',
        categoty:'jeans',
        season:'',
        loc:'',
        size:['s','l','xl','xxl'],
        color:["black","blue","beige"],
        images:["https://m.media-amazon.com/images/I/71a03OHZiVL._UY679_.jpg","https://m.media-amazon.com/images/I/61xFEBIwiwL._UY550_.jpg",'https://m.media-amazon.com/images/I/81w96fpJjcL._SY550._SX._UX._SY._UY_.jpg','https://m.media-amazon.com/images/I/718LoOaI2fL._SY550._SX._UX._SY._UY_.jpg'],
        instructions:['Care Instructions:Machine Wash','Fit Type: Regular Fit','Fabric :cotton ','High Rise','Length(inches): XS(26)-39, S(28)-39, M(30)-39, L(32)-39, XL(34)-39','Waist(inches): XS(26)-25, S(28)-27, M(30)-29, L(32)-31, XL(34)-33; Hip(inches): XS(26)-33, S(28)-35, M(30)-37, L(32)-39, XL(34)-41','To choose the right size- please refer Wide Leg size chart and how to measure image','Elasticated Waistband','Zip Fly With 2 Button Closure Elasticated Waistband']
    },
    {
        name:'ulticolor Ankle-Length Leggings',
        brand:'STYLE GRID',
        rating:3,
        noOfRatings:598,
        price:599,
        off:67,
        gender:'female',
        categoty:'jeans',
        season:'',
        loc:'',
        size:['xl'],
        color:["multicolor"],
        images:["https://m.media-amazon.com/images/I/71tkGmUvkKL._UX679_.jpg"],
        instructions:['Care Instructions:Machine Wash','Fit Type: Regular Fit','Fabric :cotton ','Size: Free size, fit to waist size between 24 inches to 32 inches. Length -37 inches,Order Strictly According to Waist Size.','High Rise','To choose the right size- please refer Wide Leg size chart and how to measure image','Elasticated Waistband','Zip Fly With 2 Button Closure Elasticated Waistband','Long-lasting and no color loss even after multiple washes.']
    },
    {
        name:' Polyester Wear Saree',
        brand:'Shiv Textiles',
        rating:4,
        noOfRatings:1268,
        price:949,
        off:62,
        gender:'female',
        categoty:'saree',
        season:'',
        loc:'',
        size:[],
        color:["blue","pink","yellow"],
        images:["https://m.media-amazon.com/images/I/410Kw-Y21XL._UX522_.jpg","https://m.media-amazon.com/images/I/41+suBosmwL._UX522_.jpg",'https://m.media-amazon.com/images/I/41ii8q1admL._UX522_.jpg',"https://m.media-amazon.com/images/I/71PlM3dYIHL._SY550._SX._UX._SY._UY_.jpg","https://m.media-amazon.com/images/I/81P285LyhiL._SY500._SX._UX._SY._UY_.jpg","https://m.media-amazon.com/images/I/71MK5rUI-kL._SY550._SX._UX._SY._UY_.jpg"],
        instructions:['Care Instructions: Hand Wash Only','Material : Soft Cotton','Design : Lucknowi Chikankari Hand Weaving Work','Style : The Texture And Weight Of The Saree Brings Image Prints One Step Closer To The Originals And Invites Attention','Occasion : Sarees for women, festive, traditional saree. Best birth-day gift for your loved ones. Each piece is elegantly crafted and will surely add to your wardrobe','This Is Pre Stitched Saree Ready To Wear || You Will Get Ready For Party In One Minute Saree For Women','Latest design sarees for women: Trendy and contemporary sarees with modern designs and patterns, keeping up with the latest fashion trends for women.']
    },
   
    {
        name:' Lace Georgette Saree',
        brand:'SIRIL',
        rating:4,
        noOfRatings:1570,
        price:1999,
        off:74,
        gender:'female',
        categoty:'saree',
        season:'',
        loc:'',
        size:[],
        color:["yellow","black","red","coral pink"],
        images:["https://m.media-amazon.com/images/I/71h1lAi7c5L._UY550_.jpg","https://m.media-amazon.com/images/I/81AcvJxe-lL._UY550_.jpg",'https://m.media-amazon.com/images/I/81DjIb8WOmL._UY550_.jpg',"image.png","https://m.media-amazon.com/images/I/81P285LyhiL._SY500._SX._UX._SY._UY_.jpg","https://m.media-amazon.com/images/I/71QQVt38r3L._SY550._SX._UX._SY._UY_.jpg","https://m.media-amazon.com/images/I/71vnAfwbVDL._SY550._SX._UX._SY._UY_.jpg","https://m.media-amazon.com/images/I/71c-a9uroJL._SY550._SX._UX._SY._UY_.jpg"],
        instructions:['Care Instructions: Hand Wash Only','Material : Soft Cotton','Design : Lucknowi Chikankari Hand Weaving Work','Style : The Texture And Weight Of The Saree Brings Image Prints One Step Closer To The Originals And Invites Attention','Occasion : Sarees for women, festive, traditional saree. Best birth-day gift for your loved ones. Each piece is elegantly crafted and will surely add to your wardrobe','This Is Pre Stitched Saree Ready To Wear || You Will Get Ready For Party In One Minute Saree For Women','Latest design sarees for women: Trendy and contemporary sarees with modern designs and patterns, keeping up with the latest fashion trends for women.']
    },
    {
        name:' Golden Zari Butta Saree ',
        brand:'leeza store',
        rating:3,
        noOfRatings:549,
        price:549,
        off:74,
        gender:'female',
        categoty:'saree',
        season:'',
        loc:'',
        size:[],
        color:["maroon","black","red","coral pink"],
        images:["https://m.media-amazon.com/images/I/919Uu73NihL._UY679_.jpg","https://m.media-amazon.com/images/I/A15KLoZanBL._UY550_.jpg",'https://m.media-amazon.com/images/I/91Y-Bsq7rwL._UY550_.jpg',"https://m.media-amazon.com/images/I/91onVV4FakL._SY550._SX._UX._SY._UY_.jpg","https://m.media-amazon.com/images/I/81P285LyhiL._SY500._SX._UX._SY._UY_.jpg","https://m.media-amazon.com/images/I/91SlckUXtQL._SY550._SX._UX._SY._UY_.jpg","https://m.media-amazon.com/images/I/91m5psjohWL._SY550._SX._UX._SY._UY_.jpg"],
        instructions:['Care Instructions: Hand Wash Only','Type: Banarasi Traditional Saree','Fabric: Saree: Lichi Silk Blend','Blouse: Poly Silk','Style : The Texture And Weight Of The Saree Brings Image Prints One Step Closer To The Originals And Invites Attention','Occasion : Sarees for women, festive, traditional saree. Best birth-day gift for your loved ones. Each piece is elegantly crafted and will surely add to your wardrobe','This Is Pre Stitched Saree Ready To Wear || You Will Get Ready For Party In One Minute Saree For Women','Latest design sarees for women: Trendy and contemporary sarees with modern designs and patterns, keeping up with the latest fashion trends for women.']
    },
    {
        name:' Brasso Printed Saree ',
        brand:'Winza',
        rating:3,
        noOfRatings:649,
        price:5549,
        off:74,
        gender:'female',
        categoty:'saree',
        season:'',
        loc:'',
        size:[],
        color:["purple","black","red","rama"],
        images:["https://m.media-amazon.com/images/I/81NszQM5rfL._UY550_.jpg","https://m.media-amazon.com/images/I/81Upuxz5T2L._UY550_.jpg",'https://m.media-amazon.com/images/I/81QADki5nmL._UY550_.jpg',"https://m.media-amazon.com/images/I/81P9bztDd0L._SY550._SX._UX._SY._UY_.jpg","https://m.media-amazon.com/images/I/8147EAvnApL._SY550._SX._UX._SY._UY_.jpg",],
        instructions:['Care Instructions: Hand Wash Only','Type: Banarasi Traditional Saree','Fabric: Saree: Lichi Silk Blend','Blouse: Poly Silk','Style : The Texture And Weight Of The Saree Brings Image Prints One Step Closer To The Originals And Invites Attention','Occasion : Sarees for women, festive, traditional saree. Best birth-day gift for your loved ones. Each piece is elegantly crafted and will surely add to your wardrobe','This Is Pre Stitched Saree Ready To Wear || You Will Get Ready For Party In One Minute Saree For Women','Latest design sarees for women: Trendy and contemporary sarees with modern designs and patterns, keeping up with the latest fashion trends for women.']
    },
   
]